/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BangDiem;
import model.LopHP;
import model.MonHoc;

/**
 *
 * @author My PC
 */
public class frmBangDiem extends javax.swing.JFrame {
    private void HienThi(){
        Vector tieuDe = new Vector();
            Label_TenSV.setText(null);
            Label_DTB.setText(null);
            tieuDe.add("Mã lớp học phần");
            tieuDe.add("Tên lớp học phần");
            tieuDe.add("Mã học phần");
            tieuDe.add("Học phần");
            tieuDe.add("Bài Tập");
            tieuDe.add("Giữa Kỳ");
            tieuDe.add("Cuối Kỳ");
            tieuDe.add("Trung Bình");
            tieuDe.add("Xếp Loại");
         Vector duLieu = new Vector();
        
         DefaultTableModel model = new DefaultTableModel(duLieu,tieuDe );
            jTable1.setModel(model); 
    }
    /**
     * Creates new form BangDiem
     */
    public frmBangDiem() {
        initComponents();
        HienThi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_XemBangDiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_IDSV_BangDiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Label_DTB = new javax.swing.JLabel();
        Label_TenSV = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_XemBangDiem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_XemBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mark.jpg"))); // NOI18N
        btn_XemBangDiem.setText("XEM BẢNG ĐIỂM");
        btn_XemBangDiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_XemBangDiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_XemBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XemBangDiemActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("XEM BẢNG ĐIỂM SINH VIÊN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("ID Sinh Viên");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoBangDiem.png"))); // NOI18N

        Label_DTB.setText("jLabel4");

        Label_TenSV.setText("jLabel4");

        jLabel4.setText("Tên sinh viên:");

        jLabel5.setText("Điểm trung bình:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_XemBangDiem)
                                    .addComponent(txt_IDSV_BangDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_DTB)
                            .addComponent(Label_TenSV))))
                .addContainerGap(834, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_TenSV)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_IDSV_BangDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_XemBangDiem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_DTB)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_XemBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XemBangDiemActionPerformed
        // TODO add your handling code here:
        if(txt_IDSV_BangDiem.getText().length()==0)
                {
                    JOptionPane.showMessageDialog(this,"Bạn chưa nhập ID Sinh viên","Thông báo",2);
            }else{
             try {
                        
                        String IDSV = new String();
                        IDSV = txt_IDSV_BangDiem.getText();
                        Connection connection = controller.connectDB.connectSQLServer();
                        PreparedStatement command = connection.prepareStatement("Select * from SINHVIEN where ID_SV=?");
                        command.setString(1, IDSV);
                        ResultSet rs = command.executeQuery();
                        if (rs.next()) {
                            
                                Label_TenSV.setText(rs.getString("TenSV"));
                                
                                Label_DTB.setText(String.valueOf((controller.BangDiemController.DiemTrungBinhID(IDSV))));
                                
                                
                                Vector tieuDe = new Vector();

                                tieuDe.add("Mã lớp học phần");
                                tieuDe.add("Tên lớp học phần");
                                tieuDe.add("Mã học phần");
                                tieuDe.add("Học phần");
                                tieuDe.add("Bài Tập");
                                tieuDe.add("Giữa Kỳ");
                                tieuDe.add("Cuối Kỳ");
                                tieuDe.add("Trung Bình");
                                tieuDe.add("Xếp Loại");
                                List<BangDiem> listBangDiem = controller.BangDiemController.listBangDiem(IDSV);
                                List<LopHP> listLopHP= controller.LopHPController.listLopHPID();
                                List<MonHoc> listMonHoc= controller.MonHocController.listMonHocID();
                                 Vector duLieu = new Vector();
                                if(listBangDiem!=null){
                                for(BangDiem bangDiem: listBangDiem){
                                        Vector tam = new Vector();
                                        tam.add(bangDiem.getID_LOPHP());
                                        for (LopHP lopHP : listLopHP){
                                            if (lopHP.getID_LopHP().equalsIgnoreCase(bangDiem.getID_LOPHP())) {
                                            tam.add(lopHP.getTenLopHP());
                                            break;           
                                        }
                                        }
                                
                                tam.add(bangDiem.getID_MH());
                                for (MonHoc monHoc : listMonHoc){
                                    if (monHoc.getID_MH().equalsIgnoreCase(bangDiem.getID_MH())) {
                                    tam.add(monHoc.getTenMH());
                                    break;           
                                }
                                }
                   
                                if (bangDiem.getBaiTap()==-1) tam.add(" "); else tam.add(bangDiem.getBaiTap());
                                if (bangDiem.getGiuaKy()==-1) tam.add(" "); else tam.add(bangDiem.getGiuaKy());
                                if (bangDiem.getCuoiKy()==-1) tam.add(" "); else tam.add(bangDiem.getCuoiKy());
                                if (bangDiem.getTrungBinh()==-1) tam.add(" "); else tam.add(bangDiem.getTrungBinh());
                                tam.add(bangDiem.getXepLoai());
                                duLieu.add(tam);

                                }
                                    DefaultTableModel model = new DefaultTableModel(duLieu,tieuDe );
                                    jTable1.setModel(model); 
                                } 
                                 }else{
                                      JOptionPane.showMessageDialog(null, "Lỗi dữ liệu", "Thông báo", JOptionPane.ERROR_MESSAGE);
                                }
                                } catch (ClassNotFoundException ex) {
                                        Logger.getLogger(frmBangDiem.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (SQLException ex) {
                                    Logger.getLogger(frmBangDiem.class.getName()).log(Level.SEVERE, null, ex);
                                }
                        
                }
        
    }//GEN-LAST:event_btn_XemBangDiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBangDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_DTB;
    private javax.swing.JLabel Label_TenSV;
    private javax.swing.JButton btn_XemBangDiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_IDSV_BangDiem;
    // End of variables declaration//GEN-END:variables
}
