
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChucVu;

/**
 *
 * @author My PC
 */
public class frmChucVu extends javax.swing.JFrame {
private void Run_QLChucVu(){
     try {
            Vector tieuDe = new Vector();
            tieuDe.add("Mã chức vụ");
            tieuDe.add("Chức vụ");
            Vector duLieu = new Vector();
            List<ChucVu> listChucVu = controller.ChucVuController.listChucVuID();
            if (listChucVu != null){
            for (ChucVu chucVu : listChucVu) {
                Vector tam = new Vector();
                tam.add(chucVu.getID_CV());
                tam.add(chucVu.getTenCV());
                duLieu.add(tam);
            }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableChucVu.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmChucVu.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * Creates new form NewJFrame
     */
    public frmChucVu() {
        initComponents();
         Run_QLChucVu();
         
                
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_Add_ChucVu = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtChucVuID_DialogAddChucVu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtChucVu_DialogAddChucVu = new javax.swing.JTextField();
        btnAddChucVu_DialogChucVu = new javax.swing.JButton();
        Dialog_Edit_ChucVu = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        txtChucVuID_DialogEditChucVu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtChucVu_DialogEditChucVu = new javax.swing.JTextField();
        btnEditChucVu_DialogChucVu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        addChucVu = new javax.swing.JButton();
        editChucVu = new javax.swing.JButton();
        deleteChucVu = new javax.swing.JButton();
        refreshChucVu = new javax.swing.JButton();
        exitChucVu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChucVu = new javax.swing.JTable();

        Dialog_Add_ChucVu.setTitle("Thêm Chức vụ");

        jLabel1.setText("Mã chức vụ");

        txtChucVuID_DialogAddChucVu.setEditable(false);

        jLabel3.setText("Chức vụ");

        btnAddChucVu_DialogChucVu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAddChucVu_DialogChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnAddChucVu_DialogChucVu.setText("Lưu");
        btnAddChucVu_DialogChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddChucVu_DialogChucVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Add_ChucVuLayout = new javax.swing.GroupLayout(Dialog_Add_ChucVu.getContentPane());
        Dialog_Add_ChucVu.getContentPane().setLayout(Dialog_Add_ChucVuLayout);
        Dialog_Add_ChucVuLayout.setHorizontalGroup(
            Dialog_Add_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_Add_ChucVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Add_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Dialog_Add_ChucVuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtChucVuID_DialogAddChucVu))
                    .addGroup(Dialog_Add_ChucVuLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Add_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dialog_Add_ChucVuLayout.createSequentialGroup()
                                .addComponent(btnAddChucVu_DialogChucVu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE))
                            .addComponent(txtChucVu_DialogAddChucVu))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        Dialog_Add_ChucVuLayout.setVerticalGroup(
            Dialog_Add_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Add_ChucVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Add_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChucVuID_DialogAddChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_Add_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtChucVu_DialogAddChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddChucVu_DialogChucVu)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Dialog_Edit_ChucVu.setTitle("Sửa Chức Vụ");

        jLabel4.setText("Mã chức vụ");

        txtChucVuID_DialogEditChucVu.setEditable(false);

        jLabel5.setText("Chức vụ");

        btnEditChucVu_DialogChucVu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEditChucVu_DialogChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnEditChucVu_DialogChucVu.setText("Lưu");
        btnEditChucVu_DialogChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditChucVu_DialogChucVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Edit_ChucVuLayout = new javax.swing.GroupLayout(Dialog_Edit_ChucVu.getContentPane());
        Dialog_Edit_ChucVu.getContentPane().setLayout(Dialog_Edit_ChucVuLayout);
        Dialog_Edit_ChucVuLayout.setHorizontalGroup(
            Dialog_Edit_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Edit_ChucVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Edit_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Dialog_Edit_ChucVuLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtChucVuID_DialogEditChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Dialog_Edit_ChucVuLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Dialog_Edit_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChucVu_DialogEditChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditChucVu_DialogChucVu))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dialog_Edit_ChucVuLayout.setVerticalGroup(
            Dialog_Edit_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Edit_ChucVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Edit_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtChucVuID_DialogEditChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_Edit_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtChucVu_DialogEditChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditChucVu_DialogChucVu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý chức vụ");

        addChucVu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addChucVu.setForeground(new java.awt.Color(0, 0, 255));
        addChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Them.png"))); // NOI18N
        addChucVu.setText("Thêm");
        addChucVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addChucVu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChucVuActionPerformed(evt);
            }
        });

        editChucVu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        editChucVu.setForeground(new java.awt.Color(0, 0, 255));
        editChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sua.png"))); // NOI18N
        editChucVu.setText("Sửa");
        editChucVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editChucVu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editChucVuActionPerformed(evt);
            }
        });

        deleteChucVu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deleteChucVu.setForeground(new java.awt.Color(0, 0, 255));
        deleteChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        deleteChucVu.setText("Xóa");
        deleteChucVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteChucVu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteChucVuActionPerformed(evt);
            }
        });

        refreshChucVu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        refreshChucVu.setForeground(new java.awt.Color(0, 0, 255));
        refreshChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LamTuoi.png"))); // NOI18N
        refreshChucVu.setText("Làm tươi");
        refreshChucVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshChucVu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshChucVuActionPerformed(evt);
            }
        });

        exitChucVu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        exitChucVu.setForeground(new java.awt.Color(0, 0, 255));
        exitChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        exitChucVu.setText("Thoát");
        exitChucVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitChucVu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitChucVuActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 153));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ CHỨC VỤ");

        tableChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableChucVu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addChucVu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editChucVu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteChucVu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshChucVu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitChucVu)
                .addGap(0, 955, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addChucVu)
                    .addComponent(editChucVu)
                    .addComponent(deleteChucVu)
                    .addComponent(refreshChucVu)
                    .addComponent(exitChucVu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddChucVu_DialogChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddChucVu_DialogChucVuActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (txtChucVu_DialogAddChucVu.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên chức vụ", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtChucVuID_DialogAddChucVu.requestFocus();
                return;
            }
            ChucVu chucvu = new ChucVu(txtChucVuID_DialogAddChucVu.getText(),txtChucVu_DialogAddChucVu.getText());
            int ketQua = controller.ChucVuController.addChucVu(chucvu);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Thêm mới chức vụ thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLChucVu();
                Dialog_Add_ChucVu.dispose();
                //
            } else {
                JOptionPane.showMessageDialog(null, "Them mới chức vụ không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmChucVu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddChucVu_DialogChucVuActionPerformed

    private void btnEditChucVu_DialogChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditChucVu_DialogChucVuActionPerformed
        // TODO add your handling code here:
        try {
            if (txtChucVu_DialogEditChucVu.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chua nhập tên chức vụ", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtChucVu_DialogEditChucVu.requestFocus();
                return;
            }
            ChucVu chucVu = new ChucVu(txtChucVuID_DialogEditChucVu.getText(), txtChucVu_DialogEditChucVu.getText());
            chucVu.setID_CV(txtChucVuID_DialogEditChucVu.getText());
            chucVu.setTenCV(txtChucVu_DialogEditChucVu.getText());
            int ketQua = controller.ChucVuController.editChucVu(chucVu);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Sửa chức vụ thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLChucVu();
                Dialog_Edit_ChucVu.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Sửa chúc vụ không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmChucVu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditChucVu_DialogChucVuActionPerformed

    private void addChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChucVuActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            txtChucVuID_DialogAddChucVu.setText(controller.ChucVuController.createChucVuID());
            Dialog_Add_ChucVu.setSize(300, 160);
            Dialog_Add_ChucVu.setLocationRelativeTo(null);
            Dialog_Add_ChucVu.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmChucVu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addChucVuActionPerformed

    private void editChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editChucVuActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableChucVu.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn chức vụ cần sửa", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtChucVu_DialogEditChucVu.requestFocus();
            return;
        }
 
        txtChucVuID_DialogEditChucVu.setText(tableChucVu.getValueAt(selectedRow, 0).toString());
        txtChucVu_DialogEditChucVu.setText(tableChucVu.getValueAt(selectedRow, 1).toString());
        Dialog_Edit_ChucVu.setSize(300, 160);
        Dialog_Edit_ChucVu.setLocationRelativeTo(null);
        Dialog_Edit_ChucVu.setVisible(true);
    }//GEN-LAST:event_editChucVuActionPerformed

    private void deleteChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteChucVuActionPerformed
        // TODO add your handling code here:
        if (tableChucVu.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn chức vụ cần xóa!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String chucVuID = tableChucVu.getValueAt(tableChucVu.getSelectedRow(), 0).toString();
                if (controller.ChucVuController.deleteChucVuID(chucVuID) == 1) {
                    JOptionPane.showMessageDialog(null, "Xoa thành công chức vụ có ID " + chucVuID, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    Run_QLChucVu();
                } else {
                    JOptionPane.showMessageDialog(null, "Xoa không thành công chức vụ có ID " + chucVuID, "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(frmChucVu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteChucVuActionPerformed

    private void refreshChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshChucVuActionPerformed
        // TODO add your handling code here:
        Run_QLChucVu();
    }//GEN-LAST:event_refreshChucVuActionPerformed

    private void exitChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitChucVuActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitChucVuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChucVu().setVisible(true);
                  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_Add_ChucVu;
    private javax.swing.JDialog Dialog_Edit_ChucVu;
    private javax.swing.JButton addChucVu;
    private javax.swing.JButton btnAddChucVu_DialogChucVu;
    private javax.swing.JButton btnEditChucVu_DialogChucVu;
    private javax.swing.JButton deleteChucVu;
    private javax.swing.JButton editChucVu;
    private javax.swing.JButton exitChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshChucVu;
    private javax.swing.JTable tableChucVu;
    private javax.swing.JTextField txtChucVuID_DialogAddChucVu;
    private javax.swing.JTextField txtChucVuID_DialogEditChucVu;
    private javax.swing.JTextField txtChucVu_DialogAddChucVu;
    private javax.swing.JTextField txtChucVu_DialogEditChucVu;
    // End of variables declaration//GEN-END:variables
}
