/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.LopHP;
import model.NhanVien;
import model.SinhVien;
import model.ThuHocPhi;

/**
 *
 * @author Dell
 */
public class frmDaThanhToan extends javax.swing.JFrame {

    /**
     * Creates new form frmDaThanhToan
     */
    public frmDaThanhToan() {
        initComponents();
        Run_DaThanhToan();
    }
    
       private void Run_DaThanhToan(){
     try {
         Label_KetQuaTimKiem.setText(null);
            Vector tieuDe = new Vector();
            tieuDe.add("Mã lớp học phần");
            tieuDe.add("Tên lớp học phần");
            tieuDe.add("Mã sinh viên");
            tieuDe.add("Tên sinh viên");
            tieuDe.add("Mã nhân viên");
            tieuDe.add("Tên nhân viên");
            tieuDe.add("Học phí");
//            tieuDe.add("ThanhToan");
            
            Vector duLieu = new Vector();
            List<ThuHocPhi> listThuHocPhi = controller.ThuHocPhiController.listDaThanhToan();
            List<LopHP> listLopHP = controller.LopHPController.listLopHPID();
            List<SinhVien> listSinhVien = controller.SinhVienController.listSinhVienID();     
            List<NhanVien> listNhanVien = controller.NhanVienController.listNhanVienID();
            if (listThuHocPhi != null){
            for (ThuHocPhi thuhocphi : listThuHocPhi) {
                
                Vector tam = new Vector();
                
                
                tam.add(thuhocphi.getID_LOPHP());
                for (LopHP lopHP : listLopHP) {
                        if (lopHP.getID_LopHP().equalsIgnoreCase(thuhocphi.getID_LOPHP())) {
                            tam.add(lopHP.getTenLopHP());
                            break;
                        }
                    }
                
                tam.add(thuhocphi.getID_SV());
                for (SinhVien sinhvien : listSinhVien){
                    if (sinhvien.getID_SV().equalsIgnoreCase(thuhocphi.getID_SV())) {
                        tam.add(sinhvien.getTenSV());
                        break;
                        
                    }
                
                }
              
             
              
                
             tam.add(thuhocphi.getID_NV());
              for(NhanVien nhanvien : listNhanVien){
                  if (nhanvien.getID_NV().equalsIgnoreCase(thuhocphi.getID_NV())){
                     tam.add(nhanvien.getTenNV());
                      break;
                     
                   }
              }
              
               for(LopHP lophp : listLopHP){
                  if (lophp.getID_LopHP().equalsIgnoreCase(thuhocphi.getID_LOPHP())){
                     tam.add(lophp.getHocPhi());
                      break;
                     
                   }
              }
                //tam.add(thuhocphi.getThanhToan());
                
                duLieu.add(tam);
            }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableDaThanhToan.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmDaThanhToan.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_DaThanhToan = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_XNHuyThanhToan = new javax.swing.JButton();
        Label_IDSV_DialogHuyThanhToan = new javax.swing.JLabel();
        Label_TenSV_DialogHuyThanhToan = new javax.swing.JLabel();
        Label_IDLopHP_DialogHuyThanhToan = new javax.swing.JLabel();
        Label_TenLopHP_DialogHuyThanhToan = new javax.swing.JLabel();
        Label_HocPhi_DialogHuyThanhToan = new javax.swing.JLabel();
        Label_ThuNgan_DialogHuyThanhToan = new javax.swing.JLabel();
        Dialog_SearchSV = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        txt_SearchSV = new javax.swing.JTextField();
        btn_SearchSV_Dialog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDaThanhToan = new javax.swing.JTable();
        btn_HuyThanhToan = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        btn_LamTuoi = new javax.swing.JButton();
        btn_SearchSV = new javax.swing.JButton();
        Label_KetQuaTimKiem = new javax.swing.JLabel();

        Dialog_DaThanhToan.setTitle("Xác nhận hủy thanh toán");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã sinh viên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên sinh viên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mã lớp học phần:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tên lớp học phần");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Học phí:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Thu ngân:");

        btn_XNHuyThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_XNHuyThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/huyTT.png"))); // NOI18N
        btn_XNHuyThanhToan.setText("Xác nhận hủy thanh toán");
        btn_XNHuyThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XNHuyThanhToanActionPerformed(evt);
            }
        });

        Label_IDSV_DialogHuyThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_IDSV_DialogHuyThanhToan.setText("jLabel8");

        Label_TenSV_DialogHuyThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_TenSV_DialogHuyThanhToan.setText("jLabel9");

        Label_IDLopHP_DialogHuyThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_IDLopHP_DialogHuyThanhToan.setText("jLabel10");

        Label_TenLopHP_DialogHuyThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_TenLopHP_DialogHuyThanhToan.setText("jLabel11");

        Label_HocPhi_DialogHuyThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_HocPhi_DialogHuyThanhToan.setText("jLabel12");

        Label_ThuNgan_DialogHuyThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_ThuNgan_DialogHuyThanhToan.setText("jLabel8");

        javax.swing.GroupLayout Dialog_DaThanhToanLayout = new javax.swing.GroupLayout(Dialog_DaThanhToan.getContentPane());
        Dialog_DaThanhToan.getContentPane().setLayout(Dialog_DaThanhToanLayout);
        Dialog_DaThanhToanLayout.setHorizontalGroup(
            Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_DaThanhToanLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_XNHuyThanhToan)
                    .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(Dialog_DaThanhToanLayout.createSequentialGroup()
                            .addGap(0, 45, Short.MAX_VALUE)
                            .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(45, 45, 45)
                            .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_ThuNgan_DialogHuyThanhToan)
                                .addComponent(Label_HocPhi_DialogHuyThanhToan)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Dialog_DaThanhToanLayout.createSequentialGroup()
                            .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addGap(45, 45, 45)
                            .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_TenLopHP_DialogHuyThanhToan)
                                .addComponent(Label_IDSV_DialogHuyThanhToan)
                                .addComponent(Label_IDLopHP_DialogHuyThanhToan)
                                .addComponent(Label_TenSV_DialogHuyThanhToan)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        Dialog_DaThanhToanLayout.setVerticalGroup(
            Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_DaThanhToanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_IDSV_DialogHuyThanhToan)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Label_TenSV_DialogHuyThanhToan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Label_IDLopHP_DialogHuyThanhToan))
                .addGap(18, 18, 18)
                .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Label_TenLopHP_DialogHuyThanhToan))
                .addGap(18, 18, 18)
                .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Label_HocPhi_DialogHuyThanhToan))
                .addGap(18, 18, 18)
                .addGroup(Dialog_DaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Label_ThuNgan_DialogHuyThanhToan))
                .addGap(18, 18, 18)
                .addComponent(btn_XNHuyThanhToan)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Dialog_SearchSV.setTitle("Tìm sinh viên");

        jLabel8.setText("ID Sinh viên");

        btn_SearchSV_Dialog.setText("Tìm sinh viên");
        btn_SearchSV_Dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchSV_DialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_SearchSVLayout = new javax.swing.GroupLayout(Dialog_SearchSV.getContentPane());
        Dialog_SearchSV.getContentPane().setLayout(Dialog_SearchSVLayout);
        Dialog_SearchSVLayout.setHorizontalGroup(
            Dialog_SearchSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_SearchSVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_SearchSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_SearchSV_Dialog)
                    .addComponent(txt_SearchSV, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dialog_SearchSVLayout.setVerticalGroup(
            Dialog_SearchSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_SearchSVLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(Dialog_SearchSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_SearchSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_SearchSV_Dialog)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đã thanh toán");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH SINH VIÊN ĐÃ THANH TOÁN HỌC PHÍ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tableDaThanhToan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDaThanhToan);

        btn_HuyThanhToan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_HuyThanhToan.setForeground(new java.awt.Color(0, 0, 255));
        btn_HuyThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HuyThanhToan.png"))); // NOI18N
        btn_HuyThanhToan.setText("Hủy thanh toán");
        btn_HuyThanhToan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_HuyThanhToan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_HuyThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyThanhToanActionPerformed(evt);
            }
        });

        btn_Thoat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(0, 51, 255));
        btn_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btn_Thoat.setText("Đóng");
        btn_Thoat.setFocusable(false);
        btn_Thoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Thoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        btn_LamTuoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_LamTuoi.setForeground(new java.awt.Color(0, 0, 255));
        btn_LamTuoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LamTuoi.png"))); // NOI18N
        btn_LamTuoi.setText("Làm tươi");
        btn_LamTuoi.setFocusable(false);
        btn_LamTuoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_LamTuoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_LamTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamTuoiActionPerformed(evt);
            }
        });

        btn_SearchSV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_SearchSV.setForeground(new java.awt.Color(0, 0, 255));
        btn_SearchSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_SearchSV.setText("Tìm Kiếm");
        btn_SearchSV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_SearchSV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_SearchSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchSVActionPerformed(evt);
            }
        });

        Label_KetQuaTimKiem.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1394, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_HuyThanhToan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_SearchSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_LamTuoi)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Thoat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1374, Short.MAX_VALUE)
                    .addComponent(Label_KetQuaTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_SearchSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LamTuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_HuyThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_KetQuaTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HuyThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyThanhToanActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableDaThanhToan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Chua chon sinh vien can sua", "Thong bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Label_IDSV_DialogHuyThanhToan.setText(tableDaThanhToan.getValueAt(selectedRow, 2).toString());
        Label_TenSV_DialogHuyThanhToan.setText(tableDaThanhToan.getValueAt(selectedRow, 3).toString());
        Label_IDLopHP_DialogHuyThanhToan.setText(tableDaThanhToan.getValueAt(selectedRow, 0).toString());
        Label_TenLopHP_DialogHuyThanhToan.setText(tableDaThanhToan.getValueAt(selectedRow, 1).toString());
        Label_HocPhi_DialogHuyThanhToan.setText(tableDaThanhToan.getValueAt(selectedRow, 6).toString());
        Label_ThuNgan_DialogHuyThanhToan.setText(tableDaThanhToan.getValueAt(selectedRow, 5).toString());
        Dialog_DaThanhToan.setSize(450,350);
        Dialog_DaThanhToan.setLocationRelativeTo(null);
        Dialog_DaThanhToan.setVisible(true);
    }//GEN-LAST:event_btn_HuyThanhToanActionPerformed

    private void btn_XNHuyThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XNHuyThanhToanActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            ThuHocPhi thuhocphi = new ThuHocPhi();
            thuhocphi.setID_SV(Label_IDSV_DialogHuyThanhToan.getText());
            thuhocphi.setID_LOPHP(Label_IDLopHP_DialogHuyThanhToan.getText());
            DefaultComboBoxModel model = new DefaultComboBoxModel();
           

            int ketQua = controller.ThuHocPhiController.editHuyThanhToan(thuhocphi);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, " sinh vien thanh cong", "Thong bao", JOptionPane.INFORMATION_MESSAGE);
                Run_DaThanhToan();
                Dialog_DaThanhToan.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Them moi sinh vien khong thanh cong", "Thong bao", JOptionPane.ERROR_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmDaThanhToan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_XNHuyThanhToanActionPerformed

    private void btn_LamTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamTuoiActionPerformed
        // TODO add your handling code here:
        Run_DaThanhToan();
    }//GEN-LAST:event_btn_LamTuoiActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void btn_SearchSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchSVActionPerformed
        // TODO add your handling code here:
        txt_SearchSV.setText("");
        Dialog_SearchSV.setSize(350,125);
        Dialog_SearchSV.setLocationRelativeTo(null);
        Dialog_SearchSV.setVisible(true);
    }//GEN-LAST:event_btn_SearchSVActionPerformed

    private void btn_SearchSV_DialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchSV_DialogActionPerformed
        // TODO add your handling code here:
        try {
            Label_KetQuaTimKiem.setText(null);
            Vector tieuDe = new Vector();
            tieuDe.add("Mã lớp học phần");
            tieuDe.add("Tên lớp học phần");
            tieuDe.add("Mã sinh viên");
            tieuDe.add("Tên sinh viên");
            tieuDe.add("Mã nhân viên");
            tieuDe.add("Tên nhân viên");
            tieuDe.add("Học phí");

            Vector duLieu = new Vector();

            String IDSV = new String();
            IDSV= txt_SearchSV.getText();
            Label_KetQuaTimKiem.setText("Kết quả tìm kiếm tên sinh viên theo từ khóa: "+IDSV+". Nhấn làm tươi để xem tất cả sinh viên");

            List<ThuHocPhi> listThuHocPhi = controller.ThuHocPhiController.TKDaThanhToanSVID(IDSV);
            List<LopHP> listLopHP = controller.LopHPController.listLopHPID();
            List<SinhVien> listSinhVien = controller.SinhVienController.listSinhVienID();
             List<NhanVien> listNhanVien = controller.NhanVienController.listNhanVienID();

            if (listThuHocPhi != null){
            for (ThuHocPhi thuhocphi : listThuHocPhi) {
                
                Vector tam = new Vector();
                
                
                tam.add(thuhocphi.getID_LOPHP());
                for (LopHP lopHP : listLopHP) {
                        if (lopHP.getID_LopHP().equalsIgnoreCase(thuhocphi.getID_LOPHP())) {
                            tam.add(lopHP.getTenLopHP());
                            break;
                        }
                    }
                
                tam.add(thuhocphi.getID_SV());
                for (SinhVien sinhvien : listSinhVien){
                    if (sinhvien.getID_SV().equalsIgnoreCase(thuhocphi.getID_SV())) {
                        tam.add(sinhvien.getTenSV());
                        break;
                        
                    }
                
                }
              
             
              
                
             tam.add(thuhocphi.getID_NV());
              for(NhanVien nhanvien : listNhanVien){
                  if (nhanvien.getID_NV().equalsIgnoreCase(thuhocphi.getID_NV())){
                     tam.add(nhanvien.getTenNV());
                      break;
                     
                   }
              }
              
               for(LopHP lophp : listLopHP){
                  if (lophp.getID_LopHP().equalsIgnoreCase(thuhocphi.getID_LOPHP())){
                     tam.add(lophp.getHocPhi());
                      break;
                     
                   }
              }
                //tam.add(thuhocphi.getThanhToan());
                
                duLieu.add(tam);
            }
            }
            
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableDaThanhToan.setModel(model);
            Dialog_SearchSV.dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmDaThanhToan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SearchSV_DialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDaThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDaThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDaThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDaThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDaThanhToan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_DaThanhToan;
    private javax.swing.JDialog Dialog_SearchSV;
    private javax.swing.JLabel Label_HocPhi_DialogHuyThanhToan;
    private javax.swing.JLabel Label_IDLopHP_DialogHuyThanhToan;
    private javax.swing.JLabel Label_IDSV_DialogHuyThanhToan;
    private javax.swing.JLabel Label_KetQuaTimKiem;
    private javax.swing.JLabel Label_TenLopHP_DialogHuyThanhToan;
    private javax.swing.JLabel Label_TenSV_DialogHuyThanhToan;
    private javax.swing.JLabel Label_ThuNgan_DialogHuyThanhToan;
    private javax.swing.JButton btn_HuyThanhToan;
    private javax.swing.JButton btn_LamTuoi;
    private javax.swing.JButton btn_SearchSV;
    private javax.swing.JButton btn_SearchSV_Dialog;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_XNHuyThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDaThanhToan;
    private javax.swing.JTextField txt_SearchSV;
    // End of variables declaration//GEN-END:variables
}
