/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.ChucVu;
import model.NhanVien;

/**
 *
 * @author My PC
 */
public class frmDSNhanVien extends javax.swing.JFrame {
    List<ChucVu> listChucVu = null;

    
private void ResetTable(){
            Vector tieuDe = new Vector();
            tieuDe.add("Mã nhân viên");
            tieuDe.add("Tên nhân viên");
            tieuDe.add("Chức vụ");
            tieuDe.add("Giới tính");
            tieuDe.add("Số CMND");
            tieuDe.add("Ngày sinh");
            tieuDe.add("Địa chỉ");
            tieuDe.add("Lương");
            Vector duLieu = new Vector();
   
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableNhanVien.setModel(model);
            
            
}
private void Run_DSNhanVien(){
     try {
         Label_DSNV.setText("Danh sách tất cả nhân viên ");
            List<ChucVu> listChucVu = controller.ChucVuController.listChucVuID();
            Vector tieuDe = new Vector();
            tieuDe.add("Mã nhân viên");
            tieuDe.add("Tên nhân viên");
            tieuDe.add("Chức vụ");
            tieuDe.add("Giới tính");
            tieuDe.add("Số CMND");
            tieuDe.add("Ngày sinh");
            tieuDe.add("Địa chỉ");
            tieuDe.add("Lương");
            Vector duLieu = new Vector();
            List<NhanVien> listNhanVien = controller.NhanVienController.listNhanVienID();
            if (listNhanVien != null) {
                for (NhanVien nhanVien : listNhanVien) {
                    Vector tam = new Vector();
                    tam.add(nhanVien.getID_NV());
                    tam.add(nhanVien.getTenNV());
                    for (ChucVu chucVu : listChucVu) {
                        if (chucVu.getID_CV().equalsIgnoreCase(nhanVien.getChucVu())) {
                            tam.add(chucVu.getTenCV());
                            break;
                        }
                    }
                    if (nhanVien.isGioitinhNV()) {
                        tam.add("Nam");
                    } else {
                        tam.add("Nữ");
                    }
                    tam.add(nhanVien.getCMND());
                      SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                    String strDate = formatter.format(nhanVien.getNgaysinhNV());
                    tam.add(strDate);
    //                tam.add(nhanVien.getNgaysinhNV());
                    tam.add(nhanVien.getDiachiNV());
                    tam.add(nhanVien.getLuong()); 
                    duLieu.add(tam);
                }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableNhanVien.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmDSNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    public frmDSNhanVien() {
        initComponents();
        Run_DSNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_DSNV_ChucVu = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        cmb_ChucVu = new javax.swing.JComboBox<>();
        btn_DSNVChucVu_Dialog = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhanVien = new javax.swing.JTable();
        Label_DSNV = new javax.swing.JLabel();
        btn_DSTatCaNV = new javax.swing.JButton();
        btn_DSNVTheoCV = new javax.swing.JButton();

        Dialog_DSNV_ChucVu.setTitle("Chọn chức vụ");

        jLabel2.setText("Chức vụ");

        cmb_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_DSNVChucVu_Dialog.setText("Lấy danh sách");
        btn_DSNVChucVu_Dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DSNVChucVu_DialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_DSNV_ChucVuLayout = new javax.swing.GroupLayout(Dialog_DSNV_ChucVu.getContentPane());
        Dialog_DSNV_ChucVu.getContentPane().setLayout(Dialog_DSNV_ChucVuLayout);
        Dialog_DSNV_ChucVuLayout.setHorizontalGroup(
            Dialog_DSNV_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_DSNV_ChucVuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(Dialog_DSNV_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_DSNVChucVu_Dialog)
                    .addComponent(cmb_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Dialog_DSNV_ChucVuLayout.setVerticalGroup(
            Dialog_DSNV_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_DSNV_ChucVuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Dialog_DSNV_ChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_DSNVChucVu_Dialog)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh sách nhân viên");

        tableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableNhanVien);

        Label_DSNV.setText("jLabel1");

        btn_DSTatCaNV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_DSTatCaNV.setForeground(new java.awt.Color(255, 153, 0));
        btn_DSTatCaNV.setText("Danh sách tất cả nhân viên");
        btn_DSTatCaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DSTatCaNVActionPerformed(evt);
            }
        });

        btn_DSNVTheoCV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_DSNVTheoCV.setForeground(new java.awt.Color(255, 153, 51));
        btn_DSNVTheoCV.setText("Danh sách nhân viên theo chức vụ");
        btn_DSNVTheoCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DSNVTheoCVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_DSNV)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_DSTatCaNV)
                        .addGap(18, 18, 18)
                        .addComponent(btn_DSNVTheoCV)))
                .addGap(0, 897, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DSTatCaNV)
                    .addComponent(btn_DSNVTheoCV))
                .addGap(18, 18, 18)
                .addComponent(Label_DSNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DSTatCaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DSTatCaNVActionPerformed
        // TODO add your handling code here:
        Run_DSNhanVien();
    }//GEN-LAST:event_btn_DSTatCaNVActionPerformed

    private void btn_DSNVTheoCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DSNVTheoCVActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here
            listChucVu = controller.ChucVuController.listChucVuID();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (ChucVu chucVu : listChucVu) {
                model.addElement(chucVu.getTenCV());
            }
            cmb_ChucVu.setModel(model);
            Dialog_DSNV_ChucVu.setSize(300,150);
            Dialog_DSNV_ChucVu.setLocationRelativeTo(null);
            Dialog_DSNV_ChucVu.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmDSNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_DSNVTheoCVActionPerformed

    private void btn_DSNVChucVu_DialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DSNVChucVu_DialogActionPerformed
        // TODO add your handling code here:
         try {
            String ID_CV = new String();
            for (ChucVu chucVu : listChucVu) {
                if (chucVu.getTenCV().equalsIgnoreCase(cmb_ChucVu.getSelectedItem().toString())) {
                    {
                        ID_CV = chucVu.getID_CV();
                         Label_DSNV.setText("Danh sách nhân viên là "+chucVu.getTenCV());
                        break;
                    }
                }
            }
            Vector tieuDe = new Vector();
             tieuDe.add("Mã nhân viên");
            tieuDe.add("Tên nhân viên");
            tieuDe.add("Chức vụ");
            tieuDe.add("Giới tính");
            tieuDe.add("Số CMND");
            tieuDe.add("Ngày sinh");
            tieuDe.add("Địa chỉ");
            tieuDe.add("Lương");
            Vector duLieu = new Vector();
      
            List<NhanVien> listNhanVien = controller.NhanVienController.listNVChucVu(ID_CV);
            if (listNhanVien != null) {
                for (NhanVien nhanVien : listNhanVien) {
                    Vector tam = new Vector();
                    tam.add(nhanVien.getID_NV());
                    tam.add(nhanVien.getTenNV());
                    
                    for (ChucVu chucVu : listChucVu) {
                        if (chucVu.getID_CV().equalsIgnoreCase(nhanVien.getChucVu())) {
                            tam.add(chucVu.getTenCV());
                            break;
                        }
                    }
                    
//                    for (ChucVu lopSH : listChucVu) {
//                        if (lopSH.getID_CV().equalsIgnoreCase(nhanVien.getChucVu())) {
//                            tam.add(nhanVien.getChucVu());
//                            break;
//                        }
//                    }
                    if (nhanVien.isGioitinhNV()) {
                        tam.add("Nam");
                    } else {
                        tam.add("Nữ");
                    }
                    tam.add(nhanVien.getCMND());
                      SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                    String strDate = formatter.format(nhanVien.getNgaysinhNV());
                    tam.add(strDate);
  //                  tam.add(nhanVien.getNgaysinhNV());
                    tam.add(nhanVien.getDiachiNV());
                     tam.add(nhanVien.getLuong()); 
                    duLieu.add(tam);
                    DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
                    tableNhanVien.setModel(model);
                }
            }else{
                 ResetTable();
            }
            
            Dialog_DSNV_ChucVu.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmDSNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmDSNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_DSNVChucVu_DialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDSNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDSNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDSNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDSNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDSNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_DSNV_ChucVu;
    private javax.swing.JLabel Label_DSNV;
    private javax.swing.JButton btn_DSNVChucVu_Dialog;
    private javax.swing.JButton btn_DSNVTheoCV;
    private javax.swing.JButton btn_DSTatCaNV;
    private javax.swing.JComboBox<String> cmb_ChucVu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNhanVien;
    // End of variables declaration//GEN-END:variables
}
