/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Encrypt.Encrypt_MD5;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

import controller.connectDB;
import model.NhanVien;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class frmdoimatkhau extends javax.swing.JFrame {

   
    public static PreparedStatement pst = null; // bien thuc thi sql
    public static ResultSet rs = null; // Ket qua tra ve 1 bang hay 1 dong du lieu
    public static Connection conn = null; // Lay tu lop co ban ket noi java
    public static Statement stt = null;
    public frmdoimatkhau() {
        initComponents();
        setLocationRelativeTo(null);
        txtIDNV.setText(frmLogin.IDNV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIDNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtxacnhanmatkhau = new javax.swing.JPasswordField();
        txtmatkhaumoi = new javax.swing.JPasswordField();
        txtmatkhaucu = new javax.swing.JPasswordField();
        butdangky = new javax.swing.JButton();
        butonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đổi mật khẩu");
        setLocation(new java.awt.Point(350, 150));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("THÔNG TIN TÀI KHOẢN");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 232)));

        jLabel2.setText("Mã Nhân Viên");

        txtIDNV.setEditable(false);

        jLabel3.setText("Mật khẩu cũ");

        jLabel4.setText("Mật khẩu mới");

        jLabel5.setText("Nhập lại mật khẩu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58)
                        .addComponent(txtIDNV))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtxacnhanmatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(txtmatkhaumoi))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtmatkhaucu))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmatkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtxacnhanmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );

        butdangky.setText("Đổi mật khẩu");
        butdangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdangkyActionPerformed(evt);
            }
        });

        butonReset.setText("Xóa tất cả");
        butonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butdangky)
                .addGap(75, 75, 75)
                .addComponent(butonReset)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butdangky)
                    .addComponent(butonReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void submit(){
        
       String sql = "SELECT * FROM NHANVIEN where ID_NV = ? and Password = ?";   
       
       try
       {
           conn = connectDB.connectSQLServer();
           pst = conn.prepareStatement(sql);
           pst.setString(1, txtIDNV.getText());
           pst.setString(2, Encrypt_MD5.encrypt(txtmatkhaucu.getText()));
           rs = pst.executeQuery();
           
           if(rs.next())
           {   
                        
                        String sqlquery = "UPDATE NHANVIEN SET Password = ? where ID_NV = ?";

                        conn = connectDB.connectSQLServer();
                        pst = conn.prepareStatement(sqlquery);

                        pst.setString(1, Encrypt_MD5.encrypt(txtmatkhaumoi.getText()));
                        pst.setString(2, this.txtIDNV.getText().trim());
                        
                       // if(this.txtmatkhaucu.getText().equals(this.txtmatkhaumoi.getText()))
                       if(Encrypt_MD5.encrypt(txtmatkhaucu.getText()).equals(Encrypt_MD5.encrypt(txtmatkhaumoi.getText())))
                        {
                            JOptionPane.showMessageDialog(null, "Mật khẩu mới giống mật khẩu cũ, Vui lòng nhập lại !","Thông báo",2);
                             this.txtmatkhaumoi.requestFocus();
                             return;
                        }
                        if(!this.txtmatkhaumoi.getText().equals(this.txtxacnhanmatkhau.getText()))
                        {
                            JOptionPane.showMessageDialog(null, "Xác nhận mật khẩu thất bại !","Thông báo",2);
                            this.txtxacnhanmatkhau.requestFocus();
                            return;
                        }
                        
                        pst.executeUpdate();
                        
                        JOptionPane.showMessageDialog(null, "Cập nhật thành công !","Thông báo",1);    
//                }
          
           }
           else{
               JOptionPane.showMessageDialog(null, "Tài khoản hoặc mật khẩu không đúng - Vui lòng nhập lại","Thông báo",2);
           }
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
    }    public void refresh(){
        this.txtmatkhaucu.setText(null);
        this.txtmatkhaumoi.setText(null);
        this.txtxacnhanmatkhau.setText(null);
    }
    private void butdangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdangkyActionPerformed
        // TODO add your handling code here:
           if(this.txtIDNV.getText().length()==0){
                JOptionPane.showMessageDialog(null,"Bạn cần nhập tài khoản để thay đổi","Thông báo",2);
                this.txtIDNV.requestFocus();
                return;
            }
            
            if(this.txtmatkhaucu.getText().length()==0){
                JOptionPane.showMessageDialog(null, "Bạn cần nhập mật khẩu cũ để thay đổi","Thông báo",2);
                this.txtmatkhaucu.requestFocus();
                return;
            }
            
            if(this.txtmatkhaumoi.getText().length()==0){
                JOptionPane.showMessageDialog(null,"Bạn cần nhập mật khẩu mới để thay đổi","Thông báo",2);
                this.txtmatkhaumoi.requestFocus();
                return;
            }
            
            if(this.txtxacnhanmatkhau.getText().length()==0){
                JOptionPane.showMessageDialog(null, "Bạn cần xác nhận mật khẩu để thay đổi","Thông báo",2);
                this.txtxacnhanmatkhau.requestFocus();
                return;
            }
            
            submit();
            refresh();
            dispose();
            
            
    }//GEN-LAST:event_butdangkyActionPerformed

    private void butonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonResetActionPerformed
        // TODO add your handling code here:
                refresh(); 
    }//GEN-LAST:event_butonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmdoimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmdoimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmdoimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmdoimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmdoimatkhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butdangky;
    private javax.swing.JButton butonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIDNV;
    private javax.swing.JPasswordField txtmatkhaucu;
    private javax.swing.JPasswordField txtmatkhaumoi;
    private javax.swing.JPasswordField txtxacnhanmatkhau;
    // End of variables declaration//GEN-END:variables
}
