/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KetQua;
import model.LopHP;
import model.SinhVien;


/**
 *
 * @author My PC
 */
public class frmKetQua extends javax.swing.JFrame {
    List<LopHP> listLopHP ;
    List<KetQua> listKetQua;
    List<SinhVien> listSinhVien;
    private void HienThi(){
         try { 
            Label_IDGV.setText(frmLogin.IDNV);
            String IDGV =  new String();
            IDGV =  Label_IDGV.getText();
            
       
            if("CVID03".equals(controller.NhanVienController.IDCV(IDGV))){
                listLopHP = controller.LopHPController.listLHPGiangVien(IDGV);
            }
            else  listLopHP = controller.LopHPController.listLopHPID();
        
            
          
            DefaultComboBoxModel model1 = new DefaultComboBoxModel();
            
            for (LopHP lopHP : listLopHP) {
                model1.addElement(lopHP.getTenLopHP());
            }
            cmbLopHP.setModel(model1);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmKetQua.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmKetQua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public frmKetQua() {
        initComponents();
        HienThi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_Edit = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_dialog_diemBT = new javax.swing.JTextField();
        text_dialog_diemGK = new javax.swing.JTextField();
        text_dialog_diemCK = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Label_IDSV = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Label_TenSV = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Label_IDLHP = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Label_LopHP = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbLopHP = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        button_AddEdit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Label_IDGV = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Bài Tập");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cuối Kỳ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Giữa Kỳ");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("IDSV:");

        Label_IDSV.setText("jLabel6");

        jLabel6.setText("Tên Sinh Viên:");

        Label_TenSV.setText("jLabel7");

        jLabel7.setText("ID Lớp học phần");

        Label_IDLHP.setText("jLabel8");

        jLabel9.setText("Lớp học phần");

        Label_LopHP.setText("jLabel10");

        javax.swing.GroupLayout dialog_EditLayout = new javax.swing.GroupLayout(dialog_Edit.getContentPane());
        dialog_Edit.getContentPane().setLayout(dialog_EditLayout);
        dialog_EditLayout.setHorizontalGroup(
            dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_EditLayout.createSequentialGroup()
                .addGroup(dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_EditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dialog_EditLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_IDLHP))
                            .addGroup(dialog_EditLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Label_IDSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)
                        .addGroup(dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_LopHP)
                            .addComponent(Label_TenSV)))
                    .addGroup(dialog_EditLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44)
                        .addGroup(dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_dialog_diemBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_dialog_diemGK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_dialog_diemCK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialog_EditLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        dialog_EditLayout.setVerticalGroup(
            dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_EditLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Label_IDLHP)
                    .addComponent(jLabel9)
                    .addComponent(Label_LopHP))
                .addGap(27, 27, 27)
                .addGroup(dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Label_TenSV)
                    .addComponent(jLabel5)
                    .addComponent(Label_IDSV))
                .addGap(18, 18, 18)
                .addGroup(dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_dialog_diemBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_dialog_diemGK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(dialog_EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_dialog_diemCK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhập điểm");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cmbLopHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLopHPActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Chọn Lớp");

        button_AddEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_AddEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mark.jpg"))); // NOI18N
        button_AddEdit.setText("Thêm/Sửa Điểm");
        button_AddEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_AddEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_AddEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AddEditActionPerformed(evt);
            }
        });

        jLabel8.setText("Mã nhân viên ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_IDGV)))
                .addGap(28, 28, 28)
                .addComponent(button_AddEdit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Label_IDGV)))
                    .addComponent(button_AddEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void reset(){
    text_dialog_diemBT.setText("");
    text_dialog_diemGK.setText("");
    text_dialog_diemCK.setText("");
}
    
private void refresh(){
 try {
            String className = cmbLopHP.getSelectedItem().toString();
     //       System.out.println(className);         
      
            String ID_LopHP = new String();
            for (LopHP lopHP : listLopHP) {
                if (lopHP.getTenLopHP().equalsIgnoreCase(className)) {
                   
                        ID_LopHP = lopHP.getID_LopHP();
                        Label_IDLHP.setText(ID_LopHP.toString());
                        Label_LopHP.setText(className.toString()); 
                        break;
                   
                }
            }
            
            Vector tieuDe = new Vector();
            
            tieuDe.add("Mã Sinh Viên");
            tieuDe.add("Tên Sinh Viên");
            tieuDe.add("Bài Tập");
            tieuDe.add("Giữa Kỳ");
            tieuDe.add("Cuối Kỳ");
            tieuDe.add("Trung Bình");
            tieuDe.add("Xếp Loại");
            
            List<SinhVien> listSinhVien= controller.SinhVienController.listSinhVienID();
            Vector duLieu = new Vector();
            List<KetQua> listKetQua = controller.KetQuaController.getKetQuaByClassName(ID_LopHP);
            if(listKetQua!=null){
                for(KetQua ketQua: listKetQua){
                    Vector tam = new Vector();
                    tam.add(ketQua.getID_SV());
                    for (SinhVien sinhvien : listSinhVien){
                    if (sinhvien.getID_SV().equalsIgnoreCase(ketQua.getID_SV())) {
                        tam.add(sinhvien.getTenSV());
                        break;           
                    }    
                }
                    if (ketQua.getBaiTap()==-1) tam.add(" "); else tam.add(ketQua.getBaiTap());
                    if (ketQua.getGiuaKy()==-1) tam.add(" "); else tam.add(ketQua.getGiuaKy());
                    if (ketQua.getCuoiKy()==-1) tam.add(" "); else tam.add(ketQua.getCuoiKy());
                    if (ketQua.getTrungBinh()==-1) tam.add(" "); else tam.add(ketQua.getTrungBinh());
                     
//                    tam.add(ketQua.getTrungBinh());
                   tam.add(ketQua.getXepLoai());
                    duLieu.add(tam);

                }
               DefaultTableModel model = new DefaultTableModel(duLieu,tieuDe );
            jTable1.setModel(model); 
            }      
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
}
    
    private void cmbLopHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLopHPActionPerformed
        refresh();

    }//GEN-LAST:event_cmbLopHPActionPerformed

    private void button_AddEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AddEditActionPerformed
          reset();
        try {
            int selectedRow = jTable1.getSelectedRow();
            
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Chua chon sinh vien", "Thong bao", JOptionPane.ERROR_MESSAGE);
                return;
            }
           
             Label_IDSV.setText(jTable1.getValueAt(selectedRow, 0).toString());
              Label_TenSV.setText(jTable1.getValueAt(selectedRow, 1).toString());
 
              if(!(jTable1.getValueAt(selectedRow, 2).toString()==(" "))){
                    text_dialog_diemBT.setText(jTable1.getValueAt(selectedRow, 2).toString());
              }
              if(!(jTable1.getValueAt(selectedRow, 3).toString()==(" "))){
                    text_dialog_diemGK.setText(jTable1.getValueAt(selectedRow, 3).toString());
              }
              if(!(jTable1.getValueAt(selectedRow, 4).toString()==(" "))){
                    text_dialog_diemCK.setText(jTable1.getValueAt(selectedRow, 4).toString());
              }
              
            
            dialog_Edit.setSize(400,300);
            dialog_Edit.setLocationRelativeTo(null);
            dialog_Edit.setVisible(true);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_button_AddEditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
         try {
        
        KetQua ketQua = new KetQua();
        
        if (text_dialog_diemBT.getText().isEmpty()) ketQua.setBaiTap(-1); else ketQua.setBaiTap(Float.parseFloat(text_dialog_diemBT.getText()));
        if (text_dialog_diemGK.getText().isEmpty())  ketQua.setGiuaKy(-1); else ketQua.setGiuaKy(Float.parseFloat(text_dialog_diemGK.getText()));          
        if (text_dialog_diemCK.getText().isEmpty()) ketQua.setCuoiKy(-1); else ketQua.setCuoiKy(Float.parseFloat(text_dialog_diemCK.getText()));
        
        if((ketQua.getGiuaKy()==-1)||(ketQua.getBaiTap()==-1)||(ketQua.getCuoiKy()==-1)){
            ketQua.setTrungBinh((float) -1.0);
            ketQua.setXepLoai(null);
        }
        else {
            ketQua.setTrungBinh((float) (0.2*ketQua.getBaiTap()+0.2*ketQua.getGiuaKy()+0.6*ketQua.getCuoiKy()));
            if (ketQua.getTrungBinh()>=8.5){
                ketQua.setXepLoai("A");
            }else if (ketQua.getTrungBinh()>=7 &&ketQua.getTrungBinh()<8.5){
                    ketQua.setXepLoai("B");
                }else if(ketQua.getTrungBinh()>=5.5 &&ketQua.getTrungBinh()<7){
                        ketQua.setXepLoai("C");
                }else if(ketQua.getTrungBinh()>=4 &&ketQua.getTrungBinh()<5.5){
                        ketQua.setXepLoai("D");    
                }else ketQua.setXepLoai("F");
        }
        
        ketQua.setID_LOPHP(Label_IDLHP.getText());
          
        ketQua.setID_SV(Label_IDSV.getText());
            int thongBao = controller.KetQuaController.editKetQua(ketQua);
            if(thongBao>0){
                 JOptionPane.showMessageDialog(null, "Cap nhat thanh cong", "Thong bao", JOptionPane.INFORMATION_MESSAGE);
                refresh();
                 dialog_Edit.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Cap nhat khong thanh cong", "Thong bao", JOptionPane.ERROR_MESSAGE);            
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmKetQua.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmKetQua.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // ADD double click
        
        //button_AddEdit.doClick();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKetQua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmKetQua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_IDGV;
    private javax.swing.JLabel Label_IDLHP;
    private javax.swing.JLabel Label_IDSV;
    private javax.swing.JLabel Label_LopHP;
    private javax.swing.JLabel Label_TenSV;
    private javax.swing.JButton button_AddEdit;
    private javax.swing.JComboBox<String> cmbLopHP;
    private javax.swing.JDialog dialog_Edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField text_dialog_diemBT;
    private javax.swing.JTextField text_dialog_diemCK;
    private javax.swing.JTextField text_dialog_diemGK;
    // End of variables declaration//GEN-END:variables
}
