/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.LopSH;

/**
 *
 * @author My PC
 */
public class frmLopSH extends javax.swing.JFrame {
private void Run_QLLopSH(){
     try {
         Label_KetQuaTimKiem.setText(null);
            Vector tieuDe = new Vector();
            tieuDe.add("Mã lớp sinh hoạt");
            tieuDe.add("Lớp sinh hoạt");
            Vector duLieu = new Vector();
            List<LopSH> listLopSH = controller.LopSHController.listLopSHID();
            if (listLopSH != null){
            for (LopSH lopSH : listLopSH) {
                Vector tam = new Vector();
                tam.add(lopSH.getID_LopSH());
                tam.add(lopSH.getTenLopSH());
                duLieu.add(tam);
            }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableLopSH.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmLopSH.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * Creates new form NewJFrame1
     */
    public frmLopSH() {
        initComponents();
        Run_QLLopSH();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_Add_LopSH = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtLopSHID_DialogAddLopSH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLopSH_DialogAddLopSH = new javax.swing.JTextField();
        btnAddLopSH_DialogLopSH = new javax.swing.JButton();
        Dialog_Edit_LopSH = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        txtLopSHID_DialogEditLopSH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLopSH_DialogEditLopSH = new javax.swing.JTextField();
        btnEditLopSH_DialogLopSH = new javax.swing.JButton();
        Dialog_Search_LopSH = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        txt_TenLSH_DialogSearch = new javax.swing.JTextField();
        btn_Search_DialogSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLopSH = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        exitLopSH = new javax.swing.JButton();
        refreshLopSH = new javax.swing.JButton();
        deleteLopSH = new javax.swing.JButton();
        editLopSH = new javax.swing.JButton();
        addLopSH = new javax.swing.JButton();
        searchLopSH = new javax.swing.JButton();
        Label_KetQuaTimKiem = new javax.swing.JLabel();

        Dialog_Add_LopSH.setTitle("Thêm lớp sinh hoạt");

        jLabel1.setText("Mã lớp SH");

        txtLopSHID_DialogAddLopSH.setEditable(false);
        txtLopSHID_DialogAddLopSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLopSHID_DialogAddLopSHActionPerformed(evt);
            }
        });

        jLabel3.setText("Lớp SH");

        btnAddLopSH_DialogLopSH.setText("Thêm");
        btnAddLopSH_DialogLopSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLopSH_DialogLopSHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Add_LopSHLayout = new javax.swing.GroupLayout(Dialog_Add_LopSH.getContentPane());
        Dialog_Add_LopSH.getContentPane().setLayout(Dialog_Add_LopSHLayout);
        Dialog_Add_LopSHLayout.setHorizontalGroup(
            Dialog_Add_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Add_LopSHLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Dialog_Add_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Dialog_Add_LopSHLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtLopSHID_DialogAddLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dialog_Add_LopSHLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Add_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddLopSH_DialogLopSH)
                            .addComponent(txtLopSH_DialogAddLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        Dialog_Add_LopSHLayout.setVerticalGroup(
            Dialog_Add_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Add_LopSHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Add_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLopSHID_DialogAddLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_Add_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLopSH_DialogAddLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddLopSH_DialogLopSH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dialog_Edit_LopSH.setTitle("Sửa lớp sinh hoạt");

        jLabel4.setText("Mã lớp SH");

        txtLopSHID_DialogEditLopSH.setEditable(false);

        jLabel5.setText("Lớp SH");

        btnEditLopSH_DialogLopSH.setText("Sửa");
        btnEditLopSH_DialogLopSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLopSH_DialogLopSHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Edit_LopSHLayout = new javax.swing.GroupLayout(Dialog_Edit_LopSH.getContentPane());
        Dialog_Edit_LopSH.getContentPane().setLayout(Dialog_Edit_LopSHLayout);
        Dialog_Edit_LopSHLayout.setHorizontalGroup(
            Dialog_Edit_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Edit_LopSHLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Dialog_Edit_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Dialog_Edit_LopSHLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtLopSHID_DialogEditLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dialog_Edit_LopSHLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Edit_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLopSH_DialogEditLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditLopSH_DialogLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        Dialog_Edit_LopSHLayout.setVerticalGroup(
            Dialog_Edit_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Edit_LopSHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Edit_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLopSHID_DialogEditLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_Edit_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLopSH_DialogEditLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditLopSH_DialogLopSH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dialog_Search_LopSH.setTitle("Tìm kiếm");

        jLabel6.setText("Tên lớp sinh hoạt");

        btn_Search_DialogSearch.setText("Tìm Kiếm");
        btn_Search_DialogSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Search_DialogSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Search_LopSHLayout = new javax.swing.GroupLayout(Dialog_Search_LopSH.getContentPane());
        Dialog_Search_LopSH.getContentPane().setLayout(Dialog_Search_LopSHLayout);
        Dialog_Search_LopSHLayout.setHorizontalGroup(
            Dialog_Search_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Search_LopSHLayout.createSequentialGroup()
                .addGroup(Dialog_Search_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Search_LopSHLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TenLSH_DialogSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dialog_Search_LopSHLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btn_Search_DialogSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dialog_Search_LopSHLayout.setVerticalGroup(
            Dialog_Search_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Search_LopSHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Search_LopSHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_TenLSH_DialogSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Search_DialogSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản Lý Lớp sinh hoạt");

        tableLopSH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableLopSH);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ LỚP SINH HOẠT");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        exitLopSH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        exitLopSH.setForeground(new java.awt.Color(0, 0, 255));
        exitLopSH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        exitLopSH.setText("Thoát");
        exitLopSH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitLopSH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitLopSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitLopSHActionPerformed(evt);
            }
        });

        refreshLopSH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        refreshLopSH.setForeground(new java.awt.Color(0, 0, 255));
        refreshLopSH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LamTuoi.png"))); // NOI18N
        refreshLopSH.setText("Làm tươi");
        refreshLopSH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshLopSH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshLopSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshLopSHActionPerformed(evt);
            }
        });

        deleteLopSH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deleteLopSH.setForeground(new java.awt.Color(0, 0, 255));
        deleteLopSH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        deleteLopSH.setText("Xóa");
        deleteLopSH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteLopSH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteLopSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLopSHActionPerformed(evt);
            }
        });

        editLopSH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        editLopSH.setForeground(new java.awt.Color(0, 0, 255));
        editLopSH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sua.png"))); // NOI18N
        editLopSH.setText("Sửa");
        editLopSH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editLopSH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editLopSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLopSHActionPerformed(evt);
            }
        });

        addLopSH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addLopSH.setForeground(new java.awt.Color(0, 0, 255));
        addLopSH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Them.png"))); // NOI18N
        addLopSH.setText("Thêm");
        addLopSH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addLopSH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addLopSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLopSHActionPerformed(evt);
            }
        });

        searchLopSH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchLopSH.setForeground(new java.awt.Color(0, 0, 255));
        searchLopSH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchLopSH.setText("Tìm kiếm");
        searchLopSH.setFocusable(false);
        searchLopSH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchLopSH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchLopSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLopSHActionPerformed(evt);
            }
        });

        Label_KetQuaTimKiem.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1323, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addLopSH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editLopSH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteLopSH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchLopSH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshLopSH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitLopSH))
                    .addComponent(Label_KetQuaTimKiem))
                .addGap(0, 781, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editLopSH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deleteLopSH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(refreshLopSH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exitLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLopSH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_KetQuaTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLopSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLopSHActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            txtLopSHID_DialogAddLopSH.setText(controller.LopSHController.createLopSHID());
            Dialog_Add_LopSH.setSize(350, 175);
            Dialog_Add_LopSH.setLocationRelativeTo(null);
            Dialog_Add_LopSH.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmLopSH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addLopSHActionPerformed

    private void editLopSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLopSHActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableLopSH.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn lớp sinh hoạt cần sửa", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtLopSH_DialogEditLopSH.requestFocus();
            return;
        }
        txtLopSHID_DialogEditLopSH.setText(tableLopSH.getValueAt(selectedRow, 0).toString());
        txtLopSH_DialogEditLopSH.setText(tableLopSH.getValueAt(selectedRow, 1).toString());
        Dialog_Edit_LopSH.setSize(350, 175);
        Dialog_Edit_LopSH.setLocationRelativeTo(null);
        Dialog_Edit_LopSH.setVisible(true);
    }//GEN-LAST:event_editLopSHActionPerformed

    private void deleteLopSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLopSHActionPerformed
        // TODO add your handling code here:
        if (tableLopSH.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn lớp sinh hoạt cần xóa!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String monHocID = tableLopSH.getValueAt(tableLopSH.getSelectedRow(), 0).toString();
                if (controller.LopSHController.deleteLopSHID(monHocID) == 1) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công lớp sinh hoạt có ID " + monHocID, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    Run_QLLopSH();
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa không thành công lớp sinh hoạt có ID " + monHocID, "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(frmLopSH.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteLopSHActionPerformed

    private void btnAddLopSH_DialogLopSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLopSH_DialogLopSHActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (txtLopSH_DialogAddLopSH.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên lớp sinh hoạt", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtLopSHID_DialogEditLopSH.requestFocus();
                return;
            }
            LopSH lopSH = new LopSH(txtLopSHID_DialogAddLopSH.getText(),txtLopSH_DialogAddLopSH.getText());
            int ketQua = controller.LopSHController.addLopSHID(lopSH);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Thêm mới lớp sinh hoạt thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLLopSH();
                Dialog_Add_LopSH.dispose();
                //
            } else {
                JOptionPane.showMessageDialog(null, "Thêm mới lớp sinh hoạt không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmLopSH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddLopSH_DialogLopSHActionPerformed

    private void btnEditLopSH_DialogLopSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLopSH_DialogLopSHActionPerformed
        // TODO add your handling code here:
        try {
            if (txtLopSH_DialogEditLopSH.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên lớp sinh hoạt", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtLopSH_DialogEditLopSH.requestFocus();
                return;
            }
            LopSH monHoc = new LopSH(txtLopSHID_DialogEditLopSH.getText(), txtLopSH_DialogEditLopSH.getText());
            monHoc.setID_LopSH(txtLopSHID_DialogEditLopSH.getText());
            monHoc.setTenLopSH(txtLopSH_DialogEditLopSH.getText());
            int ketQua = controller.LopSHController.editLopSHID(monHoc);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Sửa lớp sinh hoạt thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLLopSH();
                Dialog_Edit_LopSH.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Sửa lớp sinh hoạt không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmLopSH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditLopSH_DialogLopSHActionPerformed

    private void refreshLopSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshLopSHActionPerformed
        // TODO add your handling code here:
        Run_QLLopSH();
    }//GEN-LAST:event_refreshLopSHActionPerformed

    private void exitLopSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitLopSHActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitLopSHActionPerformed

    private void txtLopSHID_DialogAddLopSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLopSHID_DialogAddLopSHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLopSHID_DialogAddLopSHActionPerformed

    private void searchLopSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLopSHActionPerformed
        // TODO add your handling code here:

        txt_TenLSH_DialogSearch.setText("");
        Dialog_Search_LopSH.setSize(350,150);
        Dialog_Search_LopSH.setLocationRelativeTo(null);
        Dialog_Search_LopSH.setVisible(true);
    }//GEN-LAST:event_searchLopSHActionPerformed

    private void btn_Search_DialogSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Search_DialogSearchActionPerformed
        // TODO add your handling code here:

        
        try {
            Vector tieuDe = new Vector();
            tieuDe.add("Mã lớp sinh hoạt");
            tieuDe.add("Lớp sinh hoạt");
            Vector duLieu = new Vector();
            String TenLSH = new String();
            TenLSH= txt_TenLSH_DialogSearch.getText();
            Label_KetQuaTimKiem.setText("Kết quả tìm kiếm tên lớp sinh hoạt theo từ khóa: \""+TenLSH+"\". Nhấn làm tươi để xem tất cả lớp sinh hoạt");
            List<LopSH> listLopSH = controller.LopSHController.TKLopSH(TenLSH);
            if (listLopSH != null) {
                for (LopSH lopSH : listLopSH) {
                    Vector tam = new Vector();
                    tam.add(lopSH.getID_LopSH());
                    tam.add(lopSH.getTenLopSH());
                    duLieu.add(tam);
                }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableLopSH.setModel(model);
            Dialog_Search_LopSH.dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmLopSH.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_Search_DialogSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLopSH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLopSH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLopSH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLopSH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLopSH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_Add_LopSH;
    private javax.swing.JDialog Dialog_Edit_LopSH;
    private javax.swing.JDialog Dialog_Search_LopSH;
    private javax.swing.JLabel Label_KetQuaTimKiem;
    private javax.swing.JButton addLopSH;
    private javax.swing.JButton btnAddLopSH_DialogLopSH;
    private javax.swing.JButton btnEditLopSH_DialogLopSH;
    private javax.swing.JButton btn_Search_DialogSearch;
    private javax.swing.JButton deleteLopSH;
    private javax.swing.JButton editLopSH;
    private javax.swing.JButton exitLopSH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshLopSH;
    private javax.swing.JButton searchLopSH;
    private javax.swing.JTable tableLopSH;
    private javax.swing.JTextField txtLopSHID_DialogAddLopSH;
    private javax.swing.JTextField txtLopSHID_DialogEditLopSH;
    private javax.swing.JTextField txtLopSH_DialogAddLopSH;
    private javax.swing.JTextField txtLopSH_DialogEditLopSH;
    private javax.swing.JTextField txt_TenLSH_DialogSearch;
    // End of variables declaration//GEN-END:variables
}
