/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.List; 
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChucVu;
import model.LopHP;
import model.LopSH;
import model.MonHoc;
import model.NhanVien;
import model.SinhVien;

/**
 *
 * @author My PC
 */
public class frmLopHP extends javax.swing.JFrame {

    List<MonHoc> listMonHoc = null;
    List<NhanVien> listGiangVien = null;
    
    private void Run_QLLopHP(){
     try {
            Label_KetQuaTimKiem.setText(null);
            List<MonHoc> listMonHoc = controller.MonHocController.listMonHocID();
            List<NhanVien> listGiangVien = controller.NhanVienController.listGiangVienID();
            Vector tieuDe = new Vector();
            tieuDe.add("Mã lớp học phần");
            tieuDe.add("Tên lớp học phần");
            tieuDe.add("Môn học");
            tieuDe.add("Giảng viên");
            tieuDe.add("Học phí");
            Vector duLieu = new Vector();
            List<LopHP> listLopHP = controller.LopHPController.listLopHPID();
            if (listLopHP != null) {
                for (LopHP lopHP : listLopHP) {
                    Vector tam = new Vector();
                    tam.add(lopHP.getID_LopHP());
                    tam.add(lopHP.getTenLopHP());
                    for (MonHoc monHoc : listMonHoc) {
                        if (monHoc.getID_MH().equalsIgnoreCase(lopHP.getMonHoc())) {
                            tam.add(monHoc.getTenMH());
                            break;
                        }
                    }
                    for (NhanVien nhanVien : listGiangVien) {
                        if (nhanVien.getID_NV().equalsIgnoreCase(lopHP.getNhanVien())) {
                            tam.add(nhanVien.getTenNV());
                            break;
                        }
                    }
                    tam.add(lopHP.getHocPhi());
                    duLieu.add(tam);
                }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableLopHP.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmLopHP.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    
    public frmLopHP() {
        initComponents();
        Run_QLLopHP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_Add_LopHP = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        txtLHPID_DialogAddLopHP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLHP_DialogAddLopHP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbMonHoc_DialogAddLopHP = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbNhanVien_DialogAddLopHP = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtHocPhi_DialogAddLopHP = new javax.swing.JTextField();
        btnAddLopHP_DialogLopHP = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Dialog_Edit_LopHP = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        txtLHPID_DialogEditLopHP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLHP_DialogEditLopHP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbMonHoc_DialogEditLopHP = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbNhanVien_DialogEditLopHP = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtHocPhi_DialogEditLopHP = new javax.swing.JTextField();
        btnEditLopHP_DialogLopHP = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        Dialog_Search_LopHP = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        txt_TenLopHP_DialogSearch = new javax.swing.JTextField();
        btn_Search_DialogSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLopHP = new javax.swing.JTable();
        btnAddLopHP = new javax.swing.JButton();
        btnEditLopHP = new javax.swing.JButton();
        btnDeleteLopHP = new javax.swing.JButton();
        btn_LamTuoi_LopHP = new javax.swing.JButton();
        btn_Thoat_LopHP = new javax.swing.JButton();
        searchLopHP = new javax.swing.JButton();
        Label_KetQuaTimKiem = new javax.swing.JLabel();

        Dialog_Add_LopHP.setTitle("Thêm lớp học phần");

        jLabel2.setText("Mã lớp học phần");

        txtLHPID_DialogAddLopHP.setEditable(false);

        jLabel3.setText("Tên lớp học phần");

        jLabel4.setText("Môn học");

        cmbMonHoc_DialogAddLopHP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Giảng viên");

        cmbNhanVien_DialogAddLopHP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Học phí");

        btnAddLopHP_DialogLopHP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAddLopHP_DialogLopHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnAddLopHP_DialogLopHP.setText("Lưu");
        btnAddLopHP_DialogLopHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLopHP_DialogLopHPActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("THÔNG TIN LỚP HỌC PHẦN");

        javax.swing.GroupLayout Dialog_Add_LopHPLayout = new javax.swing.GroupLayout(Dialog_Add_LopHP.getContentPane());
        Dialog_Add_LopHP.getContentPane().setLayout(Dialog_Add_LopHPLayout);
        Dialog_Add_LopHPLayout.setHorizontalGroup(
            Dialog_Add_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Add_LopHPLayout.createSequentialGroup()
                .addGroup(Dialog_Add_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Add_LopHPLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel7))
                    .addGroup(Dialog_Add_LopHPLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(Dialog_Add_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Add_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddLopHP_DialogLopHP)
                            .addGroup(Dialog_Add_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLHPID_DialogAddLopHP)
                                .addComponent(txtLHP_DialogAddLopHP)
                                .addComponent(cmbMonHoc_DialogAddLopHP, 0, 200, Short.MAX_VALUE)
                                .addComponent(cmbNhanVien_DialogAddLopHP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHocPhi_DialogAddLopHP)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        Dialog_Add_LopHPLayout.setVerticalGroup(
            Dialog_Add_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_Add_LopHPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLHPID_DialogAddLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLHP_DialogAddLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMonHoc_DialogAddLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbNhanVien_DialogAddLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHocPhi_DialogAddLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddLopHP_DialogLopHP)
                .addGap(21, 21, 21))
        );

        Dialog_Edit_LopHP.setTitle("Sửa lớp học phần");

        jLabel8.setText("Mã lớp học phần");

        txtLHPID_DialogEditLopHP.setEditable(false);

        jLabel9.setText("Tên lớp họp phần");

        jLabel10.setText("Môn học");

        cmbMonHoc_DialogEditLopHP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Giảng viên");

        cmbNhanVien_DialogEditLopHP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Học phí");

        btnEditLopHP_DialogLopHP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEditLopHP_DialogLopHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnEditLopHP_DialogLopHP.setText("Lưu");
        btnEditLopHP_DialogLopHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLopHP_DialogLopHPActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("THÔNG TIN LỚP HỌC PHẦN");

        javax.swing.GroupLayout Dialog_Edit_LopHPLayout = new javax.swing.GroupLayout(Dialog_Edit_LopHP.getContentPane());
        Dialog_Edit_LopHP.getContentPane().setLayout(Dialog_Edit_LopHPLayout);
        Dialog_Edit_LopHPLayout.setHorizontalGroup(
            Dialog_Edit_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Edit_LopHPLayout.createSequentialGroup()
                .addGroup(Dialog_Edit_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Edit_LopHPLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel13))
                    .addGroup(Dialog_Edit_LopHPLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(Dialog_Edit_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Edit_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditLopHP_DialogLopHP)
                            .addGroup(Dialog_Edit_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLHPID_DialogEditLopHP)
                                .addComponent(txtLHP_DialogEditLopHP)
                                .addComponent(cmbMonHoc_DialogEditLopHP, 0, 200, Short.MAX_VALUE)
                                .addComponent(cmbNhanVien_DialogEditLopHP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHocPhi_DialogEditLopHP)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        Dialog_Edit_LopHPLayout.setVerticalGroup(
            Dialog_Edit_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_Edit_LopHPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(Dialog_Edit_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtLHPID_DialogEditLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Edit_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtLHP_DialogEditLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Edit_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbMonHoc_DialogEditLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Edit_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbNhanVien_DialogEditLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Edit_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtHocPhi_DialogEditLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEditLopHP_DialogLopHP)
                .addGap(21, 21, 21))
        );

        jMenu1.setText("jMenu1");

        Dialog_Search_LopHP.setTitle("Tìm kiếm");

        jLabel14.setText("Tên lớp học phần");

        btn_Search_DialogSearch.setText("Tìm Kiếm");
        btn_Search_DialogSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Search_DialogSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Search_LopHPLayout = new javax.swing.GroupLayout(Dialog_Search_LopHP.getContentPane());
        Dialog_Search_LopHP.getContentPane().setLayout(Dialog_Search_LopHPLayout);
        Dialog_Search_LopHPLayout.setHorizontalGroup(
            Dialog_Search_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Search_LopHPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(Dialog_Search_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Search_DialogSearch)
                    .addComponent(txt_TenLopHP_DialogSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        Dialog_Search_LopHPLayout.setVerticalGroup(
            Dialog_Search_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Search_LopHPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Search_LopHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_TenLopHP_DialogSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Search_DialogSearch)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lớp Học Phần");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ LỚP HỌC PHẦN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tableLopHP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableLopHP);

        btnAddLopHP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAddLopHP.setForeground(new java.awt.Color(0, 0, 255));
        btnAddLopHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Them.png"))); // NOI18N
        btnAddLopHP.setText("Thêm");
        btnAddLopHP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddLopHP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddLopHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLopHPActionPerformed(evt);
            }
        });

        btnEditLopHP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEditLopHP.setForeground(new java.awt.Color(0, 0, 255));
        btnEditLopHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sua.png"))); // NOI18N
        btnEditLopHP.setText("Sửa");
        btnEditLopHP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditLopHP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditLopHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLopHPActionPerformed(evt);
            }
        });

        btnDeleteLopHP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDeleteLopHP.setForeground(new java.awt.Color(0, 0, 255));
        btnDeleteLopHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnDeleteLopHP.setText("Xóa");
        btnDeleteLopHP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteLopHP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteLopHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLopHPActionPerformed(evt);
            }
        });

        btn_LamTuoi_LopHP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_LamTuoi_LopHP.setForeground(new java.awt.Color(0, 0, 255));
        btn_LamTuoi_LopHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LamTuoi.png"))); // NOI18N
        btn_LamTuoi_LopHP.setText("Làm tươi");
        btn_LamTuoi_LopHP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_LamTuoi_LopHP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_LamTuoi_LopHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamTuoi_LopHPActionPerformed(evt);
            }
        });

        btn_Thoat_LopHP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_Thoat_LopHP.setForeground(new java.awt.Color(0, 0, 255));
        btn_Thoat_LopHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btn_Thoat_LopHP.setText("Đóng");
        btn_Thoat_LopHP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Thoat_LopHP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Thoat_LopHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Thoat_LopHPActionPerformed(evt);
            }
        });

        searchLopHP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchLopHP.setForeground(new java.awt.Color(0, 0, 255));
        searchLopHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchLopHP.setText("Tìm Kiếm");
        searchLopHP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchLopHP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchLopHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLopHPActionPerformed(evt);
            }
        });

        Label_KetQuaTimKiem.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1369, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddLopHP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditLopHP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteLopHP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchLopHP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_LamTuoi_LopHP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Thoat_LopHP))
                            .addComponent(Label_KetQuaTimKiem))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamTuoi_LopHP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Thoat_LopHP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLopHP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_KetQuaTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditLopHP_DialogLopHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLopHP_DialogLopHPActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            
             if (txtLHP_DialogEditLopHP.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên lớp học phần", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtLHP_DialogEditLopHP.requestFocus();
                return;
            }
            
             if (txtHocPhi_DialogEditLopHP.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập học phí", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtHocPhi_DialogEditLopHP.requestFocus();
                return;
            }
            
            
            LopHP lopHP = new LopHP();
            lopHP.setID_LopHP(txtLHPID_DialogEditLopHP.getText());
            lopHP.setTenLopHP(txtLHP_DialogEditLopHP.getText());
            for (MonHoc monHoc : listMonHoc) {
                if (monHoc.getTenMH().equalsIgnoreCase(cmbMonHoc_DialogEditLopHP.getSelectedItem().toString())) {
                    lopHP.setMonHoc(monHoc.getID_MH());
                }
            }
            
            for (NhanVien nhanVien : listGiangVien) {
                if (nhanVien.getTenNV().equalsIgnoreCase(cmbNhanVien_DialogEditLopHP.getSelectedItem().toString())) {
                    lopHP.setNhanVien(nhanVien.getID_NV());
                }
            }
             
            lopHP.setHocPhi(Integer.parseInt(txtHocPhi_DialogEditLopHP.getText())); 
          
            int ketQua = controller.LopHPController.editLopHPID(lopHP);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, " Thêm lớp học phần thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLLopHP();
                Dialog_Edit_LopHP.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Thêm lớp học phần không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmLopHP.class.getName()).log(Level.SEVERE, null, ex);                    
        }
        
    }//GEN-LAST:event_btnEditLopHP_DialogLopHPActionPerformed

    private void btnAddLopHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLopHPActionPerformed

         try {
            // TODO add your handling code here:
            txtLHPID_DialogAddLopHP.setText(controller.LopHPController.createLopHPID());
            listMonHoc = controller.MonHocController.listMonHocID();
            DefaultComboBoxModel model1 = new DefaultComboBoxModel();
            
            for (MonHoc monHoc : listMonHoc) {
                model1.addElement(monHoc.getTenMH());
            }
            cmbMonHoc_DialogAddLopHP.setModel(model1);
            
            listGiangVien = controller.NhanVienController.listGiangVienID();
            DefaultComboBoxModel model2 = new DefaultComboBoxModel();
            for (NhanVien nhanVien : listGiangVien) {
                model2.addElement(nhanVien.getTenNV());
            }
            cmbNhanVien_DialogAddLopHP.setModel(model2);
            
            Dialog_Add_LopHP.setSize(400,350);
            Dialog_Add_LopHP.setLocationRelativeTo(null);
            Dialog_Add_LopHP.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmLopHP.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAddLopHPActionPerformed

    private void btnAddLopHP_DialogLopHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLopHP_DialogLopHPActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (txtLHP_DialogAddLopHP.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên lớp học phần", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtLHP_DialogAddLopHP.requestFocus();
                return;
            }
            
             if (txtHocPhi_DialogAddLopHP.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập học phí", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtHocPhi_DialogAddLopHP.requestFocus();
                return;
            }
            
            LopHP lopHP = new LopHP();
            lopHP.setID_LopHP(txtLHPID_DialogAddLopHP.getText());
            lopHP.setTenLopHP(txtLHP_DialogAddLopHP.getText());
            for (MonHoc monHoc : listMonHoc) {
                if (monHoc.getTenMH().equalsIgnoreCase(cmbMonHoc_DialogAddLopHP.getSelectedItem().toString())) {
                    lopHP.setMonHoc(monHoc.getID_MH());
                }
            }
            
            for (NhanVien nhanVien : listGiangVien) {
                if (nhanVien.getTenNV().equalsIgnoreCase(cmbNhanVien_DialogAddLopHP.getSelectedItem().toString())) {
                    lopHP.setNhanVien(nhanVien.getID_NV());
                }
            }
             
            lopHP.setHocPhi(Integer.parseInt(txtHocPhi_DialogAddLopHP.getText()));

            int ketQua = controller.LopHPController.addLopHPID(lopHP);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Thêm lớp học phần thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLLopHP();
                Dialog_Add_LopHP.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Thêm lớp học phần không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmLopHP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddLopHP_DialogLopHPActionPerformed

    private void btnEditLopHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLopHPActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int selectedRow = tableLopHP.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Chưa chọn lớp học phần cần sửa", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            txtLHPID_DialogEditLopHP.setText(tableLopHP.getValueAt(selectedRow, 0).toString());
            txtLHP_DialogEditLopHP.setText(tableLopHP.getValueAt(selectedRow, 1).toString());
            
            listMonHoc = controller.MonHocController.listMonHocID();
            
            DefaultComboBoxModel model1 = new DefaultComboBoxModel();
            for (MonHoc monHoc : listMonHoc) {
                model1.addElement(monHoc.getTenMH());
            }
            cmbMonHoc_DialogEditLopHP.setModel(model1);
            cmbMonHoc_DialogEditLopHP.setSelectedItem(tableLopHP.getValueAt(selectedRow, 2));
            
            
            listGiangVien = controller.NhanVienController.listGiangVienID();
            
             DefaultComboBoxModel model2 = new DefaultComboBoxModel();
            for (NhanVien nhanVien : listGiangVien) {
                model2.addElement(nhanVien.getTenNV());
            }
            cmbNhanVien_DialogEditLopHP.setModel(model2);
            cmbNhanVien_DialogEditLopHP.setSelectedItem(tableLopHP.getValueAt(selectedRow, 3));
           
            txtHocPhi_DialogEditLopHP.setText(tableLopHP.getValueAt(selectedRow, 4).toString());
                    
            Dialog_Edit_LopHP.setSize(400,350);
            Dialog_Edit_LopHP.setLocationRelativeTo(null);
            Dialog_Edit_LopHP.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmLopHP.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEditLopHPActionPerformed

    private void btnDeleteLopHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLopHPActionPerformed
        // TODO add your handling code here:
          if (tableLopHP.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn lớp học phần cần xóa!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String LHPID = tableLopHP.getValueAt(tableLopHP.getSelectedRow(), 0).toString();
                if (controller.LopHPController.deleteLopHPID(LHPID) == 1) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công lớp học phần có ID" + LHPID, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    Run_QLLopHP();
                
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa không thành công lớp học phần có ID" + LHPID, "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(frmLopHP.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteLopHPActionPerformed

    private void btn_LamTuoi_LopHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamTuoi_LopHPActionPerformed
        // TODO add your handling code here:
         Run_QLLopHP();
    }//GEN-LAST:event_btn_LamTuoi_LopHPActionPerformed

    private void btn_Thoat_LopHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Thoat_LopHPActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_Thoat_LopHPActionPerformed

    private void searchLopHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLopHPActionPerformed
        // TODO add your handling code here:
            txt_TenLopHP_DialogSearch.setText("");
            Dialog_Search_LopHP.setSize(400,150);
            Dialog_Search_LopHP.setLocationRelativeTo(null);
            Dialog_Search_LopHP.setVisible(true);
    }//GEN-LAST:event_searchLopHPActionPerformed

    private void btn_Search_DialogSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Search_DialogSearchActionPerformed
        // TODO add your handling code here:
        try {
             List<MonHoc> listMonHoc = controller.MonHocController.listMonHocID();
            List<NhanVien> listGiangVien = controller.NhanVienController.listGiangVienID();
            Vector tieuDe = new Vector();
            tieuDe.add("Mã lớp học phần");
            tieuDe.add("Tên lớp học phần");
            tieuDe.add("Môn học");
            tieuDe.add("Giảng viên");
            tieuDe.add("Học phí");
            
            Vector duLieu = new Vector();
            String TenLopHP = new String();
            TenLopHP= txt_TenLopHP_DialogSearch.getText();
             List<LopHP> listLopHP = controller.LopHPController.TKLopHP(TenLopHP);
            Label_KetQuaTimKiem.setText("Kết quả tìm kiếm tên lớp học phần theo từ khóa: \""+TenLopHP+"\". Nhấn làm tươi để xem tất cả lớp học phần");
            
            if (listLopHP != null) {
                for (LopHP lopHP : listLopHP) {
                    Vector tam = new Vector();
                    tam.add(lopHP.getID_LopHP());
                    tam.add(lopHP.getTenLopHP());
                    for (MonHoc monHoc : listMonHoc) {
                        if (monHoc.getID_MH().equalsIgnoreCase(lopHP.getMonHoc())) {
                            tam.add(monHoc.getTenMH());
                            break;
                        }
                    }
                    for (NhanVien nhanVien : listGiangVien) {
                        if (nhanVien.getID_NV().equalsIgnoreCase(lopHP.getNhanVien())) {
                            tam.add(nhanVien.getTenNV());
                            break;
                        }
                    }
                    tam.add(lopHP.getHocPhi());
                    duLieu.add(tam);
                }
            }

            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableLopHP.setModel(model);
            Dialog_Search_LopHP.dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmLopHP.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_Search_DialogSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLopHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLopHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLopHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLopHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLopHP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_Add_LopHP;
    private javax.swing.JDialog Dialog_Edit_LopHP;
    private javax.swing.JDialog Dialog_Search_LopHP;
    private javax.swing.JLabel Label_KetQuaTimKiem;
    private javax.swing.JButton btnAddLopHP;
    private javax.swing.JButton btnAddLopHP_DialogLopHP;
    private javax.swing.JButton btnDeleteLopHP;
    private javax.swing.JButton btnEditLopHP;
    private javax.swing.JButton btnEditLopHP_DialogLopHP;
    private javax.swing.JButton btn_LamTuoi_LopHP;
    private javax.swing.JButton btn_Search_DialogSearch;
    private javax.swing.JButton btn_Thoat_LopHP;
    private javax.swing.JComboBox<String> cmbMonHoc_DialogAddLopHP;
    private javax.swing.JComboBox<String> cmbMonHoc_DialogEditLopHP;
    private javax.swing.JComboBox<String> cmbNhanVien_DialogAddLopHP;
    private javax.swing.JComboBox<String> cmbNhanVien_DialogEditLopHP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchLopHP;
    private javax.swing.JTable tableLopHP;
    private javax.swing.JTextField txtHocPhi_DialogAddLopHP;
    private javax.swing.JTextField txtHocPhi_DialogEditLopHP;
    private javax.swing.JTextField txtLHPID_DialogAddLopHP;
    private javax.swing.JTextField txtLHPID_DialogEditLopHP;
    private javax.swing.JTextField txtLHP_DialogAddLopHP;
    private javax.swing.JTextField txtLHP_DialogEditLopHP;
    private javax.swing.JTextField txt_TenLopHP_DialogSearch;
    // End of variables declaration//GEN-END:variables
}
