/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChucVu;
import model.MonHoc;

/**
 *
 * @author My PC
 */
public class frmMonHoc extends javax.swing.JFrame {
private void Run_QLMonHoc(){
     try {
            Label_KetQuaTimKiem.setText(null);
            Vector tieuDe = new Vector();
            tieuDe.add("Mã môn học");
            tieuDe.add("Môn học");
            Vector duLieu = new Vector();
            List<MonHoc> listMonHoc = controller.MonHocController.listMonHocID();
            if (listMonHoc != null){
            for (MonHoc monHoc : listMonHoc) {
                Vector tam = new Vector();
                tam.add(monHoc.getID_MH());
                tam.add(monHoc.getTenMH());
                duLieu.add(tam);
            }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableMonHoc.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * Creates new form frmMH
     */
     List<MonHoc> listMonHoc = null;
    public frmMonHoc() {
        initComponents();
        Run_QLMonHoc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_Add_MonHoc = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtMonHocID_DialogAddMonHoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMonHoc_DialogAddMonHoc = new javax.swing.JTextField();
        btnAddMonHoc_DialogMonHoc = new javax.swing.JButton();
        Dialog_Edit_MonHoc = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        txtMonHocID_DialogEditMonHoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMonHoc_DialogEditMonHoc = new javax.swing.JTextField();
        btnEditMonHoc_DialogMonHoc = new javax.swing.JButton();
        Dialog_Search_MonHoc = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        txt_TenMH_DialogSearch = new javax.swing.JTextField();
        btn_Search_DialogSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMonHoc = new javax.swing.JTable();
        Label_KetQuaTimKiem = new javax.swing.JLabel();
        exitMonHoc = new javax.swing.JButton();
        refreshMonHoc = new javax.swing.JButton();
        searchMonHoc = new javax.swing.JButton();
        deleteMonHoc = new javax.swing.JButton();
        editMonHoc = new javax.swing.JButton();
        addMonHoc = new javax.swing.JButton();

        Dialog_Add_MonHoc.setTitle("Thêm môn học");

        jLabel1.setText("Mã môn học");

        txtMonHocID_DialogAddMonHoc.setEditable(false);

        jLabel3.setText("Môn học");

        btnAddMonHoc_DialogMonHoc.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAddMonHoc_DialogMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnAddMonHoc_DialogMonHoc.setText("Lưu");
        btnAddMonHoc_DialogMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMonHoc_DialogMonHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Add_MonHocLayout = new javax.swing.GroupLayout(Dialog_Add_MonHoc.getContentPane());
        Dialog_Add_MonHoc.getContentPane().setLayout(Dialog_Add_MonHocLayout);
        Dialog_Add_MonHocLayout.setHorizontalGroup(
            Dialog_Add_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Add_MonHocLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Dialog_Add_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Dialog_Add_MonHocLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtMonHocID_DialogAddMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dialog_Add_MonHocLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Add_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddMonHoc_DialogMonHoc)
                            .addComponent(txtMonHoc_DialogAddMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        Dialog_Add_MonHocLayout.setVerticalGroup(
            Dialog_Add_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Add_MonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Add_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMonHocID_DialogAddMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_Add_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMonHoc_DialogAddMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddMonHoc_DialogMonHoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dialog_Edit_MonHoc.setTitle("Sửa môn học");

        jLabel4.setText("Mã môn học");

        txtMonHocID_DialogEditMonHoc.setEditable(false);

        jLabel5.setText("Môn học");

        btnEditMonHoc_DialogMonHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEditMonHoc_DialogMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnEditMonHoc_DialogMonHoc.setText("Lưu");
        btnEditMonHoc_DialogMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMonHoc_DialogMonHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Edit_MonHocLayout = new javax.swing.GroupLayout(Dialog_Edit_MonHoc.getContentPane());
        Dialog_Edit_MonHoc.getContentPane().setLayout(Dialog_Edit_MonHocLayout);
        Dialog_Edit_MonHocLayout.setHorizontalGroup(
            Dialog_Edit_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Edit_MonHocLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Dialog_Edit_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Dialog_Edit_MonHocLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtMonHocID_DialogEditMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dialog_Edit_MonHocLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Edit_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMonHoc_DialogEditMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditMonHoc_DialogMonHoc))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        Dialog_Edit_MonHocLayout.setVerticalGroup(
            Dialog_Edit_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Edit_MonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Edit_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMonHocID_DialogEditMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_Edit_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMonHoc_DialogEditMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditMonHoc_DialogMonHoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dialog_Search_MonHoc.setTitle("Tìm kiếm");

        jLabel6.setText("Tên môn học");

        btn_Search_DialogSearch.setText("Tìm Kiếm");
        btn_Search_DialogSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Search_DialogSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Search_MonHocLayout = new javax.swing.GroupLayout(Dialog_Search_MonHoc.getContentPane());
        Dialog_Search_MonHoc.getContentPane().setLayout(Dialog_Search_MonHocLayout);
        Dialog_Search_MonHocLayout.setHorizontalGroup(
            Dialog_Search_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Search_MonHocLayout.createSequentialGroup()
                .addGroup(Dialog_Search_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Search_MonHocLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TenMH_DialogSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dialog_Search_MonHocLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btn_Search_DialogSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dialog_Search_MonHocLayout.setVerticalGroup(
            Dialog_Search_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Search_MonHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Search_MonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_TenMH_DialogSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Search_DialogSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Môn Học");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ MÔN HỌC");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tableMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMonHoc);

        Label_KetQuaTimKiem.setText("jLabel7");

        exitMonHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        exitMonHoc.setForeground(new java.awt.Color(0, 0, 255));
        exitMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        exitMonHoc.setText("Thoát");
        exitMonHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitMonHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMonHocActionPerformed(evt);
            }
        });

        refreshMonHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        refreshMonHoc.setForeground(new java.awt.Color(0, 0, 255));
        refreshMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LamTuoi.png"))); // NOI18N
        refreshMonHoc.setText("Làm tươi");
        refreshMonHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshMonHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshMonHocActionPerformed(evt);
            }
        });

        searchMonHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchMonHoc.setForeground(new java.awt.Color(51, 0, 255));
        searchMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchMonHoc.setText("Tìm kiếm");
        searchMonHoc.setFocusable(false);
        searchMonHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchMonHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMonHocActionPerformed(evt);
            }
        });

        deleteMonHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deleteMonHoc.setForeground(new java.awt.Color(0, 0, 255));
        deleteMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        deleteMonHoc.setText("Xóa");
        deleteMonHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteMonHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMonHocActionPerformed(evt);
            }
        });

        editMonHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        editMonHoc.setForeground(new java.awt.Color(0, 0, 255));
        editMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sua.png"))); // NOI18N
        editMonHoc.setText("Sửa");
        editMonHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editMonHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMonHocActionPerformed(evt);
            }
        });

        addMonHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addMonHoc.setForeground(new java.awt.Color(0, 0, 255));
        addMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Them.png"))); // NOI18N
        addMonHoc.setText("Thêm");
        addMonHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addMonHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMonHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1363, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_KetQuaTimKiem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addMonHoc)
                        .addGap(18, 18, 18)
                        .addComponent(editMonHoc)
                        .addGap(18, 18, 18)
                        .addComponent(deleteMonHoc)
                        .addGap(18, 18, 18)
                        .addComponent(searchMonHoc)
                        .addGap(18, 18, 18)
                        .addComponent(refreshMonHoc)
                        .addGap(18, 18, 18)
                        .addComponent(exitMonHoc)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_KetQuaTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMonHocActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            txtMonHocID_DialogAddMonHoc.setText(controller.MonHocController.createMonHocID());
            Dialog_Add_MonHoc.setSize(350, 175);
            Dialog_Add_MonHoc.setLocationRelativeTo(null);
            Dialog_Add_MonHoc.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addMonHocActionPerformed

    private void btnAddMonHoc_DialogMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMonHoc_DialogMonHocActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            if (txtMonHoc_DialogAddMonHoc.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên môn học", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtMonHocID_DialogAddMonHoc.requestFocus();
                return;
            }
            MonHoc monhoc = new MonHoc(txtMonHocID_DialogAddMonHoc.getText(),txtMonHoc_DialogAddMonHoc.getText());
            int ketQua = controller.MonHocController.addMonHoc(monhoc);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Thêm môn học thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLMonHoc();
                Dialog_Add_MonHoc.dispose();
                //
            } else {
                JOptionPane.showMessageDialog(null, "Thêm môn học không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddMonHoc_DialogMonHocActionPerformed

    private void editMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMonHocActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableMonHoc.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn môn học cần sửa", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtMonHoc_DialogEditMonHoc.requestFocus();
            return;
        }
        txtMonHocID_DialogEditMonHoc.setText(tableMonHoc.getValueAt(selectedRow, 0).toString());
        txtMonHoc_DialogEditMonHoc.setText(tableMonHoc.getValueAt(selectedRow, 1).toString());
        Dialog_Edit_MonHoc.setSize(350, 175);
        Dialog_Edit_MonHoc.setLocationRelativeTo(null);
        Dialog_Edit_MonHoc.setVisible(true);
    }//GEN-LAST:event_editMonHocActionPerformed

    private void btnEditMonHoc_DialogMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMonHoc_DialogMonHocActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMonHoc_DialogEditMonHoc.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên môn học", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtMonHoc_DialogEditMonHoc.requestFocus();
                return;
            }
            MonHoc monHoc = new MonHoc(txtMonHocID_DialogEditMonHoc.getText(), txtMonHoc_DialogEditMonHoc.getText());
            monHoc.setID_MH(txtMonHocID_DialogEditMonHoc.getText());
            monHoc.setTenMH(txtMonHoc_DialogEditMonHoc.getText());
            int ketQua = controller.MonHocController.editMonHoc(monHoc);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Sửa môn học thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLMonHoc();
                Dialog_Edit_MonHoc.dispose();
            
            } else {
                JOptionPane.showMessageDialog(null, "Sửa môn học không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditMonHoc_DialogMonHocActionPerformed

    private void deleteMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMonHocActionPerformed
        // TODO add your handling code here:
        if (tableMonHoc.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn môn học cần xóa!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String monHocID = tableMonHoc.getValueAt(tableMonHoc.getSelectedRow(), 0).toString();
                if (controller.MonHocController.deleteMonHocID(monHocID) == 1) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công môn học có ID " + monHocID, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    Run_QLMonHoc();
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa không thành công có môn học có ID " + monHocID, "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(frmMonHoc.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteMonHocActionPerformed

    private void refreshMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshMonHocActionPerformed
        // TODO add your handling code here:
         Run_QLMonHoc();
    }//GEN-LAST:event_refreshMonHocActionPerformed

    private void exitMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMonHocActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitMonHocActionPerformed

    private void searchMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMonHocActionPerformed
        // TODO add your handling code here:
         
            txt_TenMH_DialogSearch.setText("");
            Dialog_Search_MonHoc.setSize(375,125);
            Dialog_Search_MonHoc.setLocationRelativeTo(null);
            Dialog_Search_MonHoc.setVisible(true);
    }//GEN-LAST:event_searchMonHocActionPerformed

    private void btn_Search_DialogSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Search_DialogSearchActionPerformed
        // TODO add your handling code here:
        try {
            Vector tieuDe = new Vector();
            tieuDe.add("Mã môn học");
            tieuDe.add("Môn học");
            Vector duLieu = new Vector();
            String TenMH = new String();
            TenMH= txt_TenMH_DialogSearch.getText();
            Label_KetQuaTimKiem.setText("Kết quả tìm kiếm tên môn học theo từ khóa: \""+TenMH+"\". Nhấn làm tươi để xem tất cả môn học");
            List<MonHoc> listMonHoc = controller.MonHocController.TKMonHoc(TenMH);
            if (listMonHoc != null) {
                for (MonHoc monHoc : listMonHoc) {
                    Vector tam = new Vector();
                    tam.add(monHoc.getID_MH());
                    tam.add(monHoc.getTenMH());
                    duLieu.add(tam);
                }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableMonHoc.setModel(model);
            Dialog_Search_MonHoc.dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_Search_DialogSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMonHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_Add_MonHoc;
    private javax.swing.JDialog Dialog_Edit_MonHoc;
    private javax.swing.JDialog Dialog_Search_MonHoc;
    private javax.swing.JLabel Label_KetQuaTimKiem;
    private javax.swing.JButton addMonHoc;
    private javax.swing.JButton btnAddMonHoc_DialogMonHoc;
    private javax.swing.JButton btnEditMonHoc_DialogMonHoc;
    private javax.swing.JButton btn_Search_DialogSearch;
    private javax.swing.JButton deleteMonHoc;
    private javax.swing.JButton editMonHoc;
    private javax.swing.JButton exitMonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshMonHoc;
    private javax.swing.JButton searchMonHoc;
    private javax.swing.JTable tableMonHoc;
    private javax.swing.JTextField txtMonHocID_DialogAddMonHoc;
    private javax.swing.JTextField txtMonHocID_DialogEditMonHoc;
    private javax.swing.JTextField txtMonHoc_DialogAddMonHoc;
    private javax.swing.JTextField txtMonHoc_DialogEditMonHoc;
    private javax.swing.JTextField txt_TenMH_DialogSearch;
    // End of variables declaration//GEN-END:variables
}
