/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author My PC
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        txt_username.setText(frmLogin.IDNV);
    }

    public void setVisibleAdmin(){
    
        jMenu_HeThong.setVisible(true);
        jMenu_QuanLy.setVisible(true);
        jMenu_GiangVien.setVisible(true);
        jMenu_ThuNgan.setVisible(true);
        jMenu_DanhSach.setVisible(true);
        jMenu_TroGiup.setVisible(true);
    }
    
        public void setVisibleQuanLy(){
    
        jMenu_HeThong.setVisible(true);
        jMenu_QuanLy.setVisible(true);
        jMenu_GiangVien.setVisible(false);
        jMenu_ThuNgan.setVisible(false);
        jMenu_DanhSach.setVisible(true);
        jMenu_TroGiup.setVisible(true);
        }
        
        public void setVisibleGiangVien(){
    
        jMenu_HeThong.setVisible(true);
        jMenu_QuanLy.setVisible(false);
        jMenu_GiangVien.setVisible(true);
        jMenu_ThuNgan.setVisible(false);
        jMenu_DanhSach.setVisible(true);
        jMenu_TroGiup.setVisible(true);
        }
        
        public void setVisibleThuNgan(){
    
        jMenu_HeThong.setVisible(true);
        jMenu_QuanLy.setVisible(false);
        jMenu_GiangVien.setVisible(false);
        jMenu_ThuNgan.setVisible(true);
        jMenu_DanhSach.setVisible(true);
        jMenu_TroGiup.setVisible(true);
        }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_HeThong = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem_Exit = new javax.swing.JMenuItem();
        jMenu_QuanLy = new javax.swing.JMenu();
        jMenuItem_SinhVien = new javax.swing.JMenuItem();
        jMenuItem_NhanVien = new javax.swing.JMenuItem();
        jMenuItem_ChucVu = new javax.swing.JMenuItem();
        jMenuItem_LopSH = new javax.swing.JMenuItem();
        jMenuItem_LopHP = new javax.swing.JMenuItem();
        jMenuItem_MonHoc = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu_GiangVien = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu_ThuNgan = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu_DanhSach = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu_TroGiup = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý sinh viên");

        jLabel1.setText("Tài khoản:");
        jLabel1.setOpaque(true);

        txt_username.setText("jLabel2");

        jPanel1.setBackground(new java.awt.Color(255, 204, 41));
        jPanel1.setForeground(new java.awt.Color(255, 204, 41));

        jLabel2.setBackground(new java.awt.Color(255, 204, 41));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anhnen1.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );

        jMenu_HeThong.setText("HỆ THỐNG");

        jMenuItem1.setText("ĐĂNG XUẤT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu_HeThong.add(jMenuItem1);

        jMenuItem2.setText("ĐỔI MẬT KHẨU");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu_HeThong.add(jMenuItem2);

        jMenuItem_Exit.setText("THOÁT");
        jMenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ExitActionPerformed(evt);
            }
        });
        jMenu_HeThong.add(jMenuItem_Exit);

        jMenuBar1.add(jMenu_HeThong);

        jMenu_QuanLy.setText("QUẢN LÝ");

        jMenuItem_SinhVien.setText("Sinh Viên");
        jMenuItem_SinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SinhVienActionPerformed(evt);
            }
        });
        jMenu_QuanLy.add(jMenuItem_SinhVien);

        jMenuItem_NhanVien.setText("Nhân viên");
        jMenuItem_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NhanVienActionPerformed(evt);
            }
        });
        jMenu_QuanLy.add(jMenuItem_NhanVien);

        jMenuItem_ChucVu.setText("Chức vụ");
        jMenuItem_ChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ChucVuActionPerformed(evt);
            }
        });
        jMenu_QuanLy.add(jMenuItem_ChucVu);

        jMenuItem_LopSH.setText("Lớp sinh hoạt");
        jMenuItem_LopSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LopSHActionPerformed(evt);
            }
        });
        jMenu_QuanLy.add(jMenuItem_LopSH);

        jMenuItem_LopHP.setText("Lớp học phần");
        jMenuItem_LopHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LopHPActionPerformed(evt);
            }
        });
        jMenu_QuanLy.add(jMenuItem_LopHP);

        jMenuItem_MonHoc.setText("Môn học");
        jMenuItem_MonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MonHocActionPerformed(evt);
            }
        });
        jMenu_QuanLy.add(jMenuItem_MonHoc);

        jMenuItem3.setText("Xếp lớp");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu_QuanLy.add(jMenuItem3);

        jMenuBar1.add(jMenu_QuanLy);

        jMenu_GiangVien.setText("GIẢNG VIÊN");

        jMenuItem11.setText("Nhập điểm");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu_GiangVien.add(jMenuItem11);

        jMenuBar1.add(jMenu_GiangVien);

        jMenu_ThuNgan.setText("THU NGÂN");

        jMenuItem4.setText("Danh sách");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu_ThuNgan.add(jMenuItem4);

        jMenuItem5.setText("Chưa Thanh toán");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu_ThuNgan.add(jMenuItem5);

        jMenuItem7.setText("Đã thanh toán");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu_ThuNgan.add(jMenuItem7);

        jMenuBar1.add(jMenu_ThuNgan);

        jMenu_DanhSach.setText("DANH SÁCH");

        jMenuItem6.setText("Danh sách nhân viên");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu_DanhSach.add(jMenuItem6);

        jMenuItem9.setText("Danh sách sinh viên");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu_DanhSach.add(jMenuItem9);

        jMenuItem12.setText("Danh sách lớp học phần");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu_DanhSach.add(jMenuItem12);

        jMenuItem10.setText("Bảng điểm");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu_DanhSach.add(jMenuItem10);

        jMenuBar1.add(jMenu_DanhSach);

        jMenu_TroGiup.setText("TRỢ GIÚP");

        jMenuItem8.setText("About");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu_TroGiup.add(jMenuItem8);

        jMenuBar1.add(jMenu_TroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_username)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_username)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jMenuItem_ExitActionPerformed

    private void jMenuItem_SinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SinhVienActionPerformed
        // TODO add your handling code here:
        new frmSinhVien().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_SinhVienActionPerformed

    private void jMenuItem_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NhanVienActionPerformed
        // TODO add your handling code here:
         new frmNhanVien().setVisible(true);
    }//GEN-LAST:event_jMenuItem_NhanVienActionPerformed

    private void jMenuItem_ChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ChucVuActionPerformed
        // TODO add your handling code here:
          new frmChucVu().setVisible(true);
    }//GEN-LAST:event_jMenuItem_ChucVuActionPerformed

    private void jMenuItem_LopSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LopSHActionPerformed
        // TODO add your handling code here:
         new frmLopSH().setVisible(true);
    }//GEN-LAST:event_jMenuItem_LopSHActionPerformed

    private void jMenuItem_LopHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LopHPActionPerformed
        // TODO add your handling code here:
         new frmLopHP().setVisible(true);
    }//GEN-LAST:event_jMenuItem_LopHPActionPerformed

    private void jMenuItem_MonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MonHocActionPerformed
        // TODO add your handling code here:
         new frmMonHoc().setVisible(true);
    }//GEN-LAST:event_jMenuItem_MonHocActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new frmdoimatkhau().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new frmThuHocPhi().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new frmChuaThanhToan().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new frmDaThanhToan().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new frmAbout().setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new frmLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
          new frmXepLop().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new frmKetQua().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new frmDSNhanVien().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new frmDSSinhVien().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new frmBangDiem().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new frmDSLopHP().setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem_ChucVu;
    private javax.swing.JMenuItem jMenuItem_Exit;
    private javax.swing.JMenuItem jMenuItem_LopHP;
    private javax.swing.JMenuItem jMenuItem_LopSH;
    private javax.swing.JMenuItem jMenuItem_MonHoc;
    private javax.swing.JMenuItem jMenuItem_NhanVien;
    private javax.swing.JMenuItem jMenuItem_SinhVien;
    private javax.swing.JMenu jMenu_DanhSach;
    private javax.swing.JMenu jMenu_GiangVien;
    private javax.swing.JMenu jMenu_HeThong;
    private javax.swing.JMenu jMenu_QuanLy;
    private javax.swing.JMenu jMenu_ThuNgan;
    private javax.swing.JMenu jMenu_TroGiup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_username;
    // End of variables declaration//GEN-END:variables

   
}
