/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.time.Instant;
import java.time.format.DateTimeParseException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChucVu;
import model.NhanVien;
import controller.NhanVienController;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author My PC
 */
public class frmNhanVien extends javax.swing.JFrame {
    List<ChucVu> listChucVu = null;
 //   private Date date;
private void Run_QLNhanVien(){
     try {
         Label_KetQuaTimKiem.setText(null);
            List<ChucVu> listChucVu = controller.ChucVuController.listChucVuID();
            Vector tieuDe = new Vector();
            tieuDe.add("Mã nhân viên");
            tieuDe.add("Tên nhân viên");
            tieuDe.add("Chức vụ");
            tieuDe.add("Giới tính");
            tieuDe.add("Số CMND");
            tieuDe.add("Ngày sinh");
            tieuDe.add("Địa chỉ");
            tieuDe.add("Lương");
            Vector duLieu = new Vector();
            List<NhanVien> listNhanVien = controller.NhanVienController.listNhanVienID();
            if (listNhanVien != null) {
                for (NhanVien nhanVien : listNhanVien) {
                    Vector tam = new Vector();
                    tam.add(nhanVien.getID_NV());
                    tam.add(nhanVien.getTenNV());
                    for (ChucVu chucVu : listChucVu) {
                        if (chucVu.getID_CV().equalsIgnoreCase(nhanVien.getChucVu())) {
                            tam.add(chucVu.getTenCV());
                            break;
                        }
                    }
                    if (nhanVien.isGioitinhNV()) {
                        tam.add("Nam");
                    } else {
                        tam.add("Nữ");
                    }
                    tam.add(nhanVien.getCMND());
                     SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                    String strDate = formatter.format(nhanVien.getNgaysinhNV());
                    tam.add(strDate);
 //                   tam.add(nhanVien.getNgaysinhNV());
                    tam.add(nhanVien.getDiachiNV());
                    tam.add(nhanVien.getLuong()); 
                    duLieu.add(tam);
                }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableNhanVien.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
}
private void Reset(){
       // txtTenNV_DialogAddNhanVien.setText("");
        txtTenNV_DialogAddNhanVien.setText("");
        txtDiachiNV_DialogAddNhanVien.setText("");
        jPasswordField1.setText("");
        txtLuongNV_DialogAddNhanVien.setText("");
        txtCMND_DialogAddNhanVien.setText("");
        java.util.Date date = new java.util.Date();
       jDateNgaysinhNV_DialogAddNhanVien.setDate(date);
        
        
        
        
    }
    /**
     * Creates new form frmNhanVien
     */
    public frmNhanVien() {
        initComponents();
        Run_QLNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_Add_NhanVien = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNVID_DialogAddNhanVien = new javax.swing.JTextField();
        txtTenNV_DialogAddNhanVien = new javax.swing.JTextField();
        radioMale_DialogAddNhanVien = new javax.swing.JRadioButton();
        radioFamale_DialogAddNhanVien = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiachiNV_DialogAddNhanVien = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        cmbChucVu_DialogAddNhanVien = new javax.swing.JComboBox<>();
        btnAddNhanVien_DialogNhanVien = new javax.swing.JButton();
        jDateNgaysinhNV_DialogAddNhanVien = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtLuongNV_DialogAddNhanVien = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        txtCMND_DialogAddNhanVien = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Dialog_Edit_NhanVien = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNVID_DialogEditNhanVien = new javax.swing.JTextField();
        txtTenNV_DialogEditNhanVien = new javax.swing.JTextField();
        radioMale_DialogEditNhanVien = new javax.swing.JRadioButton();
        radioFamale_DialogEditNhanVien = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDiachiNV_DialogEditNhanVien = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        cmbChucVu_DialogEditNhanVien = new javax.swing.JComboBox<>();
        btnEditNhanVien_DialogNhanVien = new javax.swing.JButton();
        jDateNgaysinhNV_DialogEditNhanVien = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtLuongNV_DialogEditNhanVien = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCMND_DialogEditNhanVien = new javax.swing.JTextField();
        Dialog_Reset_Password = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        txtIDNV_ResetPassword_Dialog = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        btnResetPasswordNV_Dialog = new javax.swing.JButton();
        Dialog_Search_NhanVien = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        txt_TenNV_Search = new javax.swing.JTextField();
        btn_SearchNV_Dialog = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhanVien = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        Label_KetQuaTimKiem = new javax.swing.JLabel();
        btnExitNhanVien = new javax.swing.JButton();
        btnRefreshNhanVien = new javax.swing.JButton();
        btnResetPasswordNV = new javax.swing.JButton();
        btn_SearchNV = new javax.swing.JButton();
        btnDeleteNhanVien = new javax.swing.JButton();
        btnEditNhanVien = new javax.swing.JButton();
        btnAddNhanVien = new javax.swing.JButton();

        Dialog_Add_NhanVien.setTitle("Thêm nhân viên");

        jLabel1.setText("Mã nhân viên");

        jLabel2.setText("Tên nhân viên");

        jLabel3.setText("Ngày sinh");

        jLabel4.setText("Giới tính");

        jLabel5.setText("Địa chỉ");

        jLabel7.setText("Chức vụ");

        txtNVID_DialogAddNhanVien.setEditable(false);

        buttonGroup1.add(radioMale_DialogAddNhanVien);
        radioMale_DialogAddNhanVien.setText("Nam");

        buttonGroup1.add(radioFamale_DialogAddNhanVien);
        radioFamale_DialogAddNhanVien.setText("Nữ");

        txtDiachiNV_DialogAddNhanVien.setColumns(20);
        txtDiachiNV_DialogAddNhanVien.setRows(5);
        jScrollPane2.setViewportView(txtDiachiNV_DialogAddNhanVien);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("THÔNG TIN NHÂN VIÊN");

        cmbChucVu_DialogAddNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddNhanVien_DialogNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAddNhanVien_DialogNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnAddNhanVien_DialogNhanVien.setText("Lưu");
        btnAddNhanVien_DialogNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNhanVien_DialogNhanVienActionPerformed(evt);
            }
        });

        jDateNgaysinhNV_DialogAddNhanVien.setDateFormatString("dd/MM/yyyy");

        jLabel9.setText("Lương");

        password.setText("Password");

        jPasswordField1.setText("jPasswordField1");

        jLabel12.setText("Số CMND");

        javax.swing.GroupLayout Dialog_Add_NhanVienLayout = new javax.swing.GroupLayout(Dialog_Add_NhanVien.getContentPane());
        Dialog_Add_NhanVien.getContentPane().setLayout(Dialog_Add_NhanVienLayout);
        Dialog_Add_NhanVienLayout.setHorizontalGroup(
            Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                        .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCMND_DialogAddNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jDateNgaysinhNV_DialogAddNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(txtLuongNV_DialogAddNhanVien))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(radioFamale_DialogAddNhanVien)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                        .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 61, Short.MAX_VALUE))
                            .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                                .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNVID_DialogAddNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(radioMale_DialogAddNhanVien)
                                        .addComponent(txtTenNV_DialogAddNhanVien)
                                        .addComponent(cmbChucVu_DialogAddNhanVien, 0, 220, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                        .addComponent(password)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnAddNhanVien_DialogNhanVien))
                    .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Dialog_Add_NhanVienLayout.setVerticalGroup(
            Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_Add_NhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNVID_DialogAddNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenNV_DialogAddNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbChucVu_DialogAddNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radioMale_DialogAddNhanVien)
                    .addComponent(radioFamale_DialogAddNhanVien))
                .addGap(21, 21, 21)
                .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateNgaysinhNV_DialogAddNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12))
                    .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCMND_DialogAddNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Add_NhanVienLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLuongNV_DialogAddNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Add_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddNhanVien_DialogNhanVien))
                    .addComponent(jLabel5))
                .addGap(15, 15, 15))
        );

        Dialog_Edit_NhanVien.setTitle("Sửa nhân viên");

        jLabel6.setText("Mã nhân viên");

        jLabel18.setText("Tên nhân viên");

        jLabel19.setText("Ngày sinh");

        jLabel20.setText("Giới tính");

        jLabel21.setText("Địa chỉ");

        jLabel22.setText("Chức vụ");

        txtNVID_DialogEditNhanVien.setEditable(false);

        buttonGroup1.add(radioMale_DialogEditNhanVien);
        radioMale_DialogEditNhanVien.setText("Nam");

        buttonGroup1.add(radioFamale_DialogEditNhanVien);
        radioFamale_DialogEditNhanVien.setText("Nữ");

        txtDiachiNV_DialogEditNhanVien.setColumns(20);
        txtDiachiNV_DialogEditNhanVien.setRows(5);
        jScrollPane4.setViewportView(txtDiachiNV_DialogEditNhanVien);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("THÔNG TIN NHÂN VIÊN");

        cmbChucVu_DialogEditNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEditNhanVien_DialogNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEditNhanVien_DialogNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnEditNhanVien_DialogNhanVien.setText("Lưu");
        btnEditNhanVien_DialogNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNhanVien_DialogNhanVienActionPerformed(evt);
            }
        });

        jDateNgaysinhNV_DialogEditNhanVien.setDateFormatString("dd/MM/yyyy");

        jLabel10.setText("Lương");

        jLabel13.setText("Số CMND");

        javax.swing.GroupLayout Dialog_Edit_NhanVienLayout = new javax.swing.GroupLayout(Dialog_Edit_NhanVien.getContentPane());
        Dialog_Edit_NhanVien.getContentPane().setLayout(Dialog_Edit_NhanVienLayout);
        Dialog_Edit_NhanVienLayout.setHorizontalGroup(
            Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Edit_NhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Edit_NhanVienLayout.createSequentialGroup()
                        .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel22))
                        .addGap(28, 28, 28)
                        .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dialog_Edit_NhanVienLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(0, 42, Short.MAX_VALUE))
                            .addGroup(Dialog_Edit_NhanVienLayout.createSequentialGroup()
                                .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radioMale_DialogEditNhanVien)
                                    .addComponent(txtTenNV_DialogEditNhanVien)
                                    .addComponent(cmbChucVu_DialogEditNhanVien, 0, 220, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_Edit_NhanVienLayout.createSequentialGroup()
                        .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Dialog_Edit_NhanVienLayout.createSequentialGroup()
                                .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Dialog_Edit_NhanVienLayout.createSequentialGroup()
                                        .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Dialog_Edit_NhanVienLayout.createSequentialGroup()
                                                .addGap(118, 118, 118)
                                                .addComponent(radioFamale_DialogEditNhanVien))
                                            .addGroup(Dialog_Edit_NhanVienLayout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(txtNVID_DialogEditNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(Dialog_Edit_NhanVienLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateNgaysinhNV_DialogEditNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(Dialog_Edit_NhanVienLayout.createSequentialGroup()
                                                .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtLuongNV_DialogEditNhanVien, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                                        .addComponent(txtCMND_DialogEditNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                                    .addComponent(btnEditNhanVien_DialogNhanVien))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Dialog_Edit_NhanVienLayout.createSequentialGroup()
                                .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel10)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        Dialog_Edit_NhanVienLayout.setVerticalGroup(
            Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_Edit_NhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Dialog_Edit_NhanVienLayout.createSequentialGroup()
                        .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNVID_DialogEditNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtTenNV_DialogEditNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(cmbChucVu_DialogEditNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(radioMale_DialogEditNhanVien)
                            .addComponent(radioFamale_DialogEditNhanVien))
                        .addGap(15, 15, 15)
                        .addComponent(jDateNgaysinhNV_DialogEditNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19))
                .addGap(10, 10, 10)
                .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCMND_DialogEditNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Edit_NhanVienLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(Dialog_Edit_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLuongNV_DialogEditNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditNhanVien_DialogNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dialog_Reset_Password.setTitle("Đặt lại mật khẩu");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("ĐẶT LẠI MẬT KHẨU NHÂN VIÊN");

        txtIDNV_ResetPassword_Dialog.setEditable(false);
        txtIDNV_ResetPassword_Dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDNV_ResetPassword_DialogActionPerformed(evt);
            }
        });

        jLabel15.setText("Mã nhân viên:");

        jLabel16.setText("Mật khẩu mới:");

        jPasswordField3.setText("jPasswordField3");

        btnResetPasswordNV_Dialog.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnResetPasswordNV_Dialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_passwordchange.png"))); // NOI18N
        btnResetPasswordNV_Dialog.setText("Đặt lại");
        btnResetPasswordNV_Dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordNV_DialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Reset_PasswordLayout = new javax.swing.GroupLayout(Dialog_Reset_Password.getContentPane());
        Dialog_Reset_Password.getContentPane().setLayout(Dialog_Reset_PasswordLayout);
        Dialog_Reset_PasswordLayout.setHorizontalGroup(
            Dialog_Reset_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Reset_PasswordLayout.createSequentialGroup()
                .addGroup(Dialog_Reset_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Reset_PasswordLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(Dialog_Reset_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(Dialog_Reset_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIDNV_ResetPassword_Dialog)
                            .addComponent(jPasswordField3)))
                    .addGroup(Dialog_Reset_PasswordLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnResetPasswordNV_Dialog)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        Dialog_Reset_PasswordLayout.setVerticalGroup(
            Dialog_Reset_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Reset_PasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_Reset_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtIDNV_ResetPassword_Dialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_Reset_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnResetPasswordNV_Dialog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dialog_Search_NhanVien.setTitle("Tìm kiếm");

        jLabel24.setText("Tên nhân viên");

        btn_SearchNV_Dialog.setText("Tìm kiếm");
        btn_SearchNV_Dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchNV_DialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Search_NhanVienLayout = new javax.swing.GroupLayout(Dialog_Search_NhanVien.getContentPane());
        Dialog_Search_NhanVien.getContentPane().setLayout(Dialog_Search_NhanVienLayout);
        Dialog_Search_NhanVienLayout.setHorizontalGroup(
            Dialog_Search_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Search_NhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Search_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Search_NhanVienLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_TenNV_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dialog_Search_NhanVienLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btn_SearchNV_Dialog)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dialog_Search_NhanVienLayout.setVerticalGroup(
            Dialog_Search_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Search_NhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Search_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_TenNV_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_SearchNV_Dialog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhân Viên");

        tableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableNhanVien);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("QUẢN LÝ NHÂN VIÊN");

        Label_KetQuaTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Label_KetQuaTimKiem.setText("jLabel10");

        btnExitNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnExitNhanVien.setForeground(new java.awt.Color(0, 0, 204));
        btnExitNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btnExitNhanVien.setText("Thoát");
        btnExitNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExitNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExitNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitNhanVienActionPerformed(evt);
            }
        });

        btnRefreshNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRefreshNhanVien.setForeground(new java.awt.Color(0, 0, 204));
        btnRefreshNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LamTuoi.png"))); // NOI18N
        btnRefreshNhanVien.setText("Làm tươi");
        btnRefreshNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefreshNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefreshNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshNhanVienActionPerformed(evt);
            }
        });

        btnResetPasswordNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnResetPasswordNV.setForeground(new java.awt.Color(0, 0, 204));
        btnResetPasswordNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resetPassword.png"))); // NOI18N
        btnResetPasswordNV.setText("Đổi mật khẩu");
        btnResetPasswordNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResetPasswordNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnResetPasswordNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordNVActionPerformed(evt);
            }
        });

        btn_SearchNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_SearchNV.setForeground(new java.awt.Color(0, 0, 204));
        btn_SearchNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_SearchNV.setText("Tìm kiếm");
        btn_SearchNV.setFocusable(false);
        btn_SearchNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_SearchNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_SearchNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchNVActionPerformed(evt);
            }
        });

        btnDeleteNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDeleteNhanVien.setForeground(new java.awt.Color(0, 0, 204));
        btnDeleteNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnDeleteNhanVien.setText("Xóa");
        btnDeleteNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNhanVienActionPerformed(evt);
            }
        });

        btnEditNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEditNhanVien.setForeground(new java.awt.Color(0, 0, 255));
        btnEditNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sua.png"))); // NOI18N
        btnEditNhanVien.setText("Sửa");
        btnEditNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNhanVienActionPerformed(evt);
            }
        });

        btnAddNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAddNhanVien.setForeground(new java.awt.Color(0, 0, 255));
        btnAddNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Them.png"))); // NOI18N
        btnAddNhanVien.setText("Thêm");
        btnAddNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_SearchNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetPasswordNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExitNhanVien)
                        .addGap(0, 772, Short.MAX_VALUE))
                    .addComponent(Label_KetQuaTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAddNhanVien)
                                        .addComponent(btnEditNhanVien, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(btnDeleteNhanVien, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(btn_SearchNV, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btnResetPasswordNV, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(btnRefreshNhanVien, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnExitNhanVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_KetQuaTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNhanVienActionPerformed
        try {
             Reset();
            // TODO add your handling code here:
            txtNVID_DialogAddNhanVien.setText(controller.NhanVienController.createNhanVienID());
            listChucVu = controller.ChucVuController.listChucVuID();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (ChucVu chucVu : listChucVu) {
                model.addElement(chucVu.getTenCV());
            }
            cmbChucVu_DialogAddNhanVien.setModel(model);
            radioMale_DialogAddNhanVien.setSelected(true);
            Dialog_Add_NhanVien.setSize(400,600);
            Dialog_Add_NhanVien.setLocationRelativeTo(null);
            Dialog_Add_NhanVien.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddNhanVienActionPerformed

    private void btnAddNhanVien_DialogNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNhanVien_DialogNhanVienActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            if (txtTenNV_DialogAddNhanVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên nhân viên", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtTenNV_DialogAddNhanVien.requestFocus();
                return;
            }
           
             if (txtDiachiNV_DialogAddNhanVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập địa chỉ nhân viên", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtDiachiNV_DialogAddNhanVien.requestFocus();
                return;
            }
             
             try{
                long n=0L;
                n = Long.parseLong(txtCMND_DialogAddNhanVien.getText());
                if(n<0) {
                    JOptionPane.showMessageDialog(null, "Chỉ nhập số ô số CMND ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
                }
            }catch(Exception ex) {
               JOptionPane.showMessageDialog(null, "Chỉ nhập số ô số CMND", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
             
            try{
                long n=0L;
                n = Long.parseLong(txtLuongNV_DialogAddNhanVien.getText());
                if(n<0) {
                    JOptionPane.showMessageDialog(null, "Chỉ nhập số ô Lương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
                }
            }catch(Exception ex) {
               JOptionPane.showMessageDialog(null, "Chỉ nhập số ô số Lương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            } 
             
            
            NhanVien nhanVien = new NhanVien();
            nhanVien.setID_NV(txtNVID_DialogAddNhanVien.getText());
            nhanVien.setTenNV(txtTenNV_DialogAddNhanVien.getText());
            nhanVien.setCMND(txtCMND_DialogAddNhanVien.getText());
            for (ChucVu chucVu : listChucVu) {
                if (chucVu.getTenCV().equalsIgnoreCase(cmbChucVu_DialogAddNhanVien.getSelectedItem().toString())) {
                    nhanVien.setChucVu(chucVu.getID_CV());
                }
            }
            
            if (radioMale_DialogAddNhanVien.isSelected()) {
                nhanVien.setGioitinhNV(true);
            } else {
                nhanVien.setGioitinhNV(false);
            }

            nhanVien.setNgaysinhNV(jDateNgaysinhNV_DialogAddNhanVien.getDate());
            
            nhanVien.setDiachiNV(txtDiachiNV_DialogAddNhanVien.getText());

            nhanVien.setLuong(Integer.parseInt(txtLuongNV_DialogAddNhanVien.getText()));

            nhanVien.setPassword(jPasswordField1.getText().toString());
      //       System.out.println("Password: "+nhanVien.getPassword());
            
            int ketQua = controller.NhanVienController.addNhanVienID(nhanVien);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Thêm mới nhân viên thành công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLNhanVien();
                Dialog_Add_NhanVien.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Thêm mới nhân viên không thành công", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddNhanVien_DialogNhanVienActionPerformed

    private void btnEditNhanVien_DialogNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNhanVien_DialogNhanVienActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            if (txtTenNV_DialogEditNhanVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên nhân viên", "Thong bao", JOptionPane.ERROR_MESSAGE);
                txtTenNV_DialogEditNhanVien.requestFocus();
                return;
            }
            
           
            if (txtDiachiNV_DialogEditNhanVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên nhân viên", "Thong bao", JOptionPane.ERROR_MESSAGE);
                txtDiachiNV_DialogEditNhanVien.requestFocus();
                return;
            }
            
            try{
                long n=0L;
                n = Long.parseLong(txtCMND_DialogEditNhanVien.getText().trim());
                if(n<0) {
                    JOptionPane.showMessageDialog(null, "Chỉ nhập số ô số CMND", "Thong bao", JOptionPane.INFORMATION_MESSAGE);
                return;
                }
            }catch(Exception ex) {
               JOptionPane.showMessageDialog(null, "Chỉ nhập số ô số CMND ", "Thong bao", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
             try{
                long n=0L;
                n = Long.parseLong(txtLuongNV_DialogEditNhanVien.getText());
                if(n<0) {
                    JOptionPane.showMessageDialog(null, "Chỉ nhập số ô Lương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
                }
            }catch(Exception ex) {
               JOptionPane.showMessageDialog(null, "Chỉ nhập số ô số Lương", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            } 
            
            NhanVien nhanVien = new NhanVien();
            nhanVien.setID_NV(txtNVID_DialogEditNhanVien.getText());
            nhanVien.setTenNV(txtTenNV_DialogEditNhanVien.getText());
            nhanVien.setCMND(txtCMND_DialogEditNhanVien.getText());
            for (ChucVu chucVu : listChucVu) {
                if (chucVu.getTenCV().equalsIgnoreCase(cmbChucVu_DialogEditNhanVien.getSelectedItem().toString())) {
                    nhanVien.setChucVu(chucVu.getID_CV());
                }
            }
            if (radioMale_DialogEditNhanVien.isSelected()) {
                nhanVien.setGioitinhNV(true);
            } else {
                nhanVien.setGioitinhNV(false);
            }
            
           nhanVien.setNgaysinhNV(jDateNgaysinhNV_DialogEditNhanVien.getDate());
            
            nhanVien.setDiachiNV(txtDiachiNV_DialogEditNhanVien.getText());
          
            nhanVien.setLuong(Integer.parseInt(txtLuongNV_DialogEditNhanVien.getText()));
            
            int ketQua = controller.NhanVienController.editNhanVienID(nhanVien);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Sửa nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLNhanVien();
                Dialog_Edit_NhanVien.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Sửa nhân viên không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEditNhanVien_DialogNhanVienActionPerformed

    private void btnEditNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNhanVienActionPerformed
        // TODO add your handling code here:
         try {
            
            int selectedRow = tableNhanVien.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Chưa chọn nhân viên cần sửa", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            txtNVID_DialogEditNhanVien.setText(tableNhanVien.getValueAt(selectedRow, 0).toString());
            txtTenNV_DialogEditNhanVien.setText(tableNhanVien.getValueAt(selectedRow, 1).toString());
            listChucVu = controller.ChucVuController.listChucVuID();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (ChucVu chucVu : listChucVu) {
                model.addElement(chucVu.getTenCV());
            }
            cmbChucVu_DialogEditNhanVien.setModel(model);
            cmbChucVu_DialogEditNhanVien.setSelectedItem(tableNhanVien.getValueAt(selectedRow, 2));
            if (tableNhanVien.getValueAt(selectedRow, 3).toString().equalsIgnoreCase("nam")) {
                radioMale_DialogEditNhanVien.setSelected(true);
            } else {
                radioFamale_DialogEditNhanVien.setSelected(true);
            }
            
            txtCMND_DialogEditNhanVien.setText(tableNhanVien.getValueAt(selectedRow, 4).toString());
 
         
            
            try
                {       
                        Date date = new SimpleDateFormat("dd/MM/yyyy").parse((String)tableNhanVien.getValueAt(selectedRow,5).toString());
                        this.jDateNgaysinhNV_DialogEditNhanVien.setDate(date);
                }catch(Exception e)
                {
                    e.printStackTrace();
                }
 //           jDateNgaysinhNV_DialogEditNhanVien.setDate(tableNhanVien.getValueAt(selectedRow, 5).);
            txtDiachiNV_DialogEditNhanVien.setText(tableNhanVien.getValueAt(selectedRow, 6).toString());
            txtLuongNV_DialogEditNhanVien.setText(tableNhanVien.getValueAt(selectedRow, 7).toString());
            Dialog_Edit_NhanVien.setSize(400,500);
            Dialog_Edit_NhanVien.setLocationRelativeTo(null);
            Dialog_Edit_NhanVien.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEditNhanVienActionPerformed

    private void btnDeleteNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNhanVienActionPerformed
        // TODO add your handling code here:
          if (tableNhanVien.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Chua chọn nhân viên cần xóa!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String NVID = tableNhanVien.getValueAt(tableNhanVien.getSelectedRow(), 0).toString();
                if (controller.NhanVienController.deleteNhanVienID(NVID) == 1) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công nhân viên có ID " + NVID, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    Run_QLNhanVien();
                
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa không thành công nhân viên có ID " + NVID, "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteNhanVienActionPerformed

    private void btnRefreshNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshNhanVienActionPerformed
        // TODO add your handling code here:
        Run_QLNhanVien();
    }//GEN-LAST:event_btnRefreshNhanVienActionPerformed

    private void btnExitNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitNhanVienActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitNhanVienActionPerformed

    private void btnResetPasswordNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordNVActionPerformed
        // TODO add your handling code here:
         
            int selectedRow = tableNhanVien.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Chưa chọn nhân viên cần đổi mật khẩu", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
           txtIDNV_ResetPassword_Dialog.setText(tableNhanVien.getValueAt(selectedRow, 0).toString());
            Dialog_Reset_Password.setSize(400,250);
            Dialog_Reset_Password.setLocationRelativeTo(null);
            Dialog_Reset_Password.setVisible(true);
        
    }//GEN-LAST:event_btnResetPasswordNVActionPerformed

    private void txtIDNV_ResetPassword_DialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDNV_ResetPassword_DialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDNV_ResetPassword_DialogActionPerformed

    private void btnResetPasswordNV_DialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordNV_DialogActionPerformed
        // TODO add your handling code here:
        try {  
        NhanVien nhanVien = new NhanVien();
          nhanVien.setID_NV(txtIDNV_ResetPassword_Dialog.getText());
          nhanVien.setPassword(jPasswordField3.getText().toString());
            int ketQua;
        
            ketQua = controller.NhanVienController.resetPassWordNhanVienID(nhanVien);
             if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLNhanVien();
                Dialog_Edit_NhanVien.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Đổi mật khẩu không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_btnResetPasswordNV_DialogActionPerformed

    private void btn_SearchNV_DialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchNV_DialogActionPerformed
        // TODO add your handling code here:
       
            List<ChucVu> listChucVu;
        try {
            listChucVu = controller.ChucVuController.listChucVuID();
       
            Vector tieuDe = new Vector();
            tieuDe.add("Mã nhân viên");
            tieuDe.add("Tên nhân viên");
            tieuDe.add("Chức vụ");
            tieuDe.add("Giới tính");
            tieuDe.add("Số CMND");
            tieuDe.add("Ngày sinh");
            tieuDe.add("Địa chỉ");
            tieuDe.add("Lương");
            Vector duLieu = new Vector();
            String TenNV = new String();
            TenNV= txt_TenNV_Search.getText();
            Label_KetQuaTimKiem.setText("Kết quả tìm kiếm tên nhân viên theo từ khóa: "+TenNV+". Nhấn làm tươi để xem tất cả nhân viên");
            List<NhanVien> listNhanVien = controller.NhanVienController.TimKiemNVTen(TenNV);
            if (listNhanVien!= null) {
                  for (NhanVien nhanVien : listNhanVien) {
                    Vector tam = new Vector();
                    tam.add(nhanVien.getID_NV());
                    tam.add(nhanVien.getTenNV());
                   for (ChucVu chucVu : listChucVu) {
                        if (chucVu.getID_CV().equalsIgnoreCase(nhanVien.getChucVu())) {
                            tam.add(chucVu.getTenCV());
                            break;
                        }
                    }
                    if (nhanVien.isGioitinhNV()) {
                        tam.add("Nam");
                    } else {
                        tam.add("Nữ");
                    }
                    tam.add(nhanVien.getCMND());
                    tam.add(nhanVien.getNgaysinhNV());
                    tam.add(nhanVien.getDiachiNV());
                    tam.add(nhanVien.getLuong()); 
                    duLieu.add(tam);
                }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableNhanVien.setModel(model);
            Dialog_Search_NhanVien.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_SearchNV_DialogActionPerformed

    private void btn_SearchNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchNVActionPerformed
        // TODO add your handling code here:
            txt_TenNV_Search.setText("");
            Dialog_Search_NhanVien.setSize(350,125);
            Dialog_Search_NhanVien.setLocationRelativeTo(null);
            Dialog_Search_NhanVien.setVisible(true);
    }//GEN-LAST:event_btn_SearchNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_Add_NhanVien;
    private javax.swing.JDialog Dialog_Edit_NhanVien;
    private javax.swing.JDialog Dialog_Reset_Password;
    private javax.swing.JDialog Dialog_Search_NhanVien;
    private javax.swing.JLabel Label_KetQuaTimKiem;
    private javax.swing.JButton btnAddNhanVien;
    private javax.swing.JButton btnAddNhanVien_DialogNhanVien;
    private javax.swing.JButton btnDeleteNhanVien;
    private javax.swing.JButton btnEditNhanVien;
    private javax.swing.JButton btnEditNhanVien_DialogNhanVien;
    private javax.swing.JButton btnExitNhanVien;
    private javax.swing.JButton btnRefreshNhanVien;
    private javax.swing.JButton btnResetPasswordNV;
    private javax.swing.JButton btnResetPasswordNV_Dialog;
    private javax.swing.JButton btn_SearchNV;
    private javax.swing.JButton btn_SearchNV_Dialog;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbChucVu_DialogAddNhanVien;
    private javax.swing.JComboBox<String> cmbChucVu_DialogEditNhanVien;
    private com.toedter.calendar.JDateChooser jDateNgaysinhNV_DialogAddNhanVien;
    private com.toedter.calendar.JDateChooser jDateNgaysinhNV_DialogEditNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel password;
    private javax.swing.JRadioButton radioFamale_DialogAddNhanVien;
    private javax.swing.JRadioButton radioFamale_DialogEditNhanVien;
    private javax.swing.JRadioButton radioMale_DialogAddNhanVien;
    private javax.swing.JRadioButton radioMale_DialogEditNhanVien;
    private javax.swing.JTable tableNhanVien;
    private javax.swing.JTextField txtCMND_DialogAddNhanVien;
    private javax.swing.JTextField txtCMND_DialogEditNhanVien;
    private javax.swing.JTextArea txtDiachiNV_DialogAddNhanVien;
    private javax.swing.JTextArea txtDiachiNV_DialogEditNhanVien;
    private javax.swing.JTextField txtIDNV_ResetPassword_Dialog;
    private javax.swing.JTextField txtLuongNV_DialogAddNhanVien;
    private javax.swing.JTextField txtLuongNV_DialogEditNhanVien;
    private javax.swing.JTextField txtNVID_DialogAddNhanVien;
    private javax.swing.JTextField txtNVID_DialogEditNhanVien;
    private javax.swing.JTextField txtTenNV_DialogAddNhanVien;
    private javax.swing.JTextField txtTenNV_DialogEditNhanVien;
    private javax.swing.JTextField txt_TenNV_Search;
    // End of variables declaration//GEN-END:variables

    
}
