/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.format.DateTimeParseException;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChucVu;
import model.LopSH;
import model.SinhVien;

/**
 *
 * @author My PC
 */
public class frmSinhVien extends javax.swing.JFrame {

    List<LopSH> listLopSH = null;
//    private Date date;
private void Run_QLSinhVien(){
     try {
            Label_KetQuaTimKiem.setText(null);
            List<LopSH> listLopSH = controller.LopSHController.listLopSHID();
            Vector tieuDe = new Vector();
            tieuDe.add("Mã sinh viên");
            tieuDe.add("Tên sinh viên");
            tieuDe.add("Lớp SH");
            tieuDe.add("Giới tính");
            tieuDe.add("Số CMND");
            tieuDe.add("Ngày sinh");
            tieuDe.add("Địa chỉ");
            Vector duLieu = new Vector();
            List<SinhVien> listSinhVien = controller.SinhVienController.listSinhVienID();
            if (listSinhVien != null) {
                for (SinhVien sinhVien : listSinhVien) {
                    Vector tam = new Vector();
                    tam.add(sinhVien.getID_SV());
                    tam.add(sinhVien.getTenSV());
                    for (LopSH lopSH : listLopSH) {
                        if (lopSH.getID_LopSH().equalsIgnoreCase(sinhVien.getLopSH())) {
                            tam.add(lopSH.getTenLopSH());
                            break;
                        }
                    }
                    if (sinhVien.isGioitinhSV()) {
                        tam.add("Nam");
                    } else {
                        tam.add("Nữ");
                    }
                    tam.add(sinhVien.getCMND());
                    
                    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                    String strDate = formatter.format(sinhVien.getNgaysinhSV());
                    tam.add(strDate);
                    
 //                   tam.add(sinhVien.getNgaysinhSV());
                    tam.add(sinhVien.getDiachiSV());
                    duLieu.add(tam);
                }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableSinhVien.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * Creates new form frmSinhVien
     */
private void Reset(){
       // txtTenNV_DialogAddNhanVien.setText("");
        txtTenSV_DialogAddSinhVien.setText("");
        txtDiachiSV_DialogAddSinhVien.setText("");
        txtCMND_DialogAddSinhVien.setText("");
        java.util.Date date = new java.util.Date();
       jDateNgaysinhSV_DialogAddSinhVien.setDate(date);
        
        
        
        
    }
    public frmSinhVien() {
        initComponents();
        Run_QLSinhVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_Add_SinhVien = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSVID_DialogAddSinhVien = new javax.swing.JTextField();
        txtTenSV_DialogAddSinhVien = new javax.swing.JTextField();
        radioMale_DialogAddSinhVien = new javax.swing.JRadioButton();
        radioFamale_DialogAddSinhVien = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiachiSV_DialogAddSinhVien = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        cmbLopSH_DialogAddSinhVien = new javax.swing.JComboBox<>();
        btnAddSinhVien_DialogSinhVien = new javax.swing.JButton();
        jDateNgaysinhSV_DialogAddSinhVien = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        txtCMND_DialogAddSinhVien = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Dialog_Edit_SinhVien = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtSVID_DialogEditSinhVien = new javax.swing.JTextField();
        txtTenSV_DialogEditSinhVien = new javax.swing.JTextField();
        radioMale_DialogEditSinhVien = new javax.swing.JRadioButton();
        radioFamale_DialogEditSinhVien = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDiachiSV_DialogEditSinhVien = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        cmbLopSH_DialogEditSinhVien = new javax.swing.JComboBox<>();
        btnEditSinhVien_DialogSinhVien = new javax.swing.JButton();
        jDateNgaysinhSV_DialogEditSinhVien = new com.toedter.calendar.JDateChooser();
        txtCMND_DialogEditSinhVien = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Dialog_Search_SinhVien = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        txt_TenSV_Search = new javax.swing.JTextField();
        btn_SearchSV_Dialog = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSinhVien = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        Label_KetQuaTimKiem = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnRefreshSinhVien = new javax.swing.JButton();
        btn_SearchSV = new javax.swing.JButton();
        btnDeleteSinhVien = new javax.swing.JButton();
        btnEditSinhVien = new javax.swing.JButton();
        btnAddSinhVien = new javax.swing.JButton();

        Dialog_Add_SinhVien.setTitle("Thêm sinh viên");

        jLabel1.setText("Mã sinh viên");

        jLabel2.setText("Tên sinh viên");

        jLabel3.setText("Ngày sinh");

        jLabel4.setText("Giới tính");

        jLabel5.setText("Địa chỉ");

        jLabel7.setText("Lớp SH");

        txtSVID_DialogAddSinhVien.setEditable(false);

        buttonGroup1.add(radioMale_DialogAddSinhVien);
        radioMale_DialogAddSinhVien.setText("Nam");

        buttonGroup1.add(radioFamale_DialogAddSinhVien);
        radioFamale_DialogAddSinhVien.setText("Nữ");

        txtDiachiSV_DialogAddSinhVien.setColumns(20);
        txtDiachiSV_DialogAddSinhVien.setRows(5);
        jScrollPane2.setViewportView(txtDiachiSV_DialogAddSinhVien);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("THÔNG TIN SINH VIÊN");

        cmbLopSH_DialogAddSinhVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddSinhVien_DialogSinhVien.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAddSinhVien_DialogSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnAddSinhVien_DialogSinhVien.setText("Lưu");
        btnAddSinhVien_DialogSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSinhVien_DialogSinhVienActionPerformed(evt);
            }
        });

        jDateNgaysinhSV_DialogAddSinhVien.setDateFormatString("dd/MM/yyyy");

        jLabel13.setText("Số CMND");

        javax.swing.GroupLayout Dialog_Add_SinhVienLayout = new javax.swing.GroupLayout(Dialog_Add_SinhVien.getContentPane());
        Dialog_Add_SinhVien.getContentPane().setLayout(Dialog_Add_SinhVienLayout);
        Dialog_Add_SinhVienLayout.setHorizontalGroup(
            Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Add_SinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Add_SinhVienLayout.createSequentialGroup()
                        .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dialog_Add_SinhVienLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(radioFamale_DialogAddSinhVien)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Dialog_Add_SinhVienLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jDateNgaysinhSV_DialogAddSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(Dialog_Add_SinhVienLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCMND_DialogAddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddSinhVien_DialogSinhVien))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(Dialog_Add_SinhVienLayout.createSequentialGroup()
                        .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dialog_Add_SinhVienLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_Add_SinhVienLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtSVID_DialogAddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
                            .addGroup(Dialog_Add_SinhVienLayout.createSequentialGroup()
                                .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radioMale_DialogAddSinhVien)
                                    .addComponent(txtTenSV_DialogAddSinhVien)
                                    .addComponent(cmbLopSH_DialogAddSinhVien, 0, 220, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(Dialog_Add_SinhVienLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Dialog_Add_SinhVienLayout.setVerticalGroup(
            Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_Add_SinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSVID_DialogAddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenSV_DialogAddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbLopSH_DialogAddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radioMale_DialogAddSinhVien)
                    .addComponent(radioFamale_DialogAddSinhVien))
                .addGap(15, 15, 15)
                .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDateNgaysinhSV_DialogAddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(txtCMND_DialogAddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(Dialog_Add_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddSinhVien_DialogSinhVien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dialog_Edit_SinhVien.setTitle("Sửa sinh viên");

        jLabel6.setText("Mã sinh viên");

        jLabel18.setText("Tên sinh viên");

        jLabel19.setText("Ngày sinh");

        jLabel20.setText("Giới tính");

        jLabel21.setText("Địa chỉ");

        jLabel22.setText("Lớp SH");

        txtSVID_DialogEditSinhVien.setEditable(false);

        buttonGroup1.add(radioMale_DialogEditSinhVien);
        radioMale_DialogEditSinhVien.setText("Nam");

        buttonGroup1.add(radioFamale_DialogEditSinhVien);
        radioFamale_DialogEditSinhVien.setText("Nữ");

        txtDiachiSV_DialogEditSinhVien.setColumns(20);
        txtDiachiSV_DialogEditSinhVien.setRows(5);
        jScrollPane4.setViewportView(txtDiachiSV_DialogEditSinhVien);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("THÔNG TIN SINH VIÊN");

        cmbLopSH_DialogEditSinhVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEditSinhVien_DialogSinhVien.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnEditSinhVien_DialogSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnEditSinhVien_DialogSinhVien.setText("Sửa");
        btnEditSinhVien_DialogSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSinhVien_DialogSinhVienActionPerformed(evt);
            }
        });

        jDateNgaysinhSV_DialogEditSinhVien.setDateFormatString("dd/MM/yyyy");

        jLabel14.setText("Số CMND");

        javax.swing.GroupLayout Dialog_Edit_SinhVienLayout = new javax.swing.GroupLayout(Dialog_Edit_SinhVien.getContentPane());
        Dialog_Edit_SinhVien.getContentPane().setLayout(Dialog_Edit_SinhVienLayout);
        Dialog_Edit_SinhVienLayout.setHorizontalGroup(
            Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Edit_SinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_Edit_SinhVienLayout.createSequentialGroup()
                        .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dialog_Edit_SinhVienLayout.createSequentialGroup()
                                .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Dialog_Edit_SinhVienLayout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(radioFamale_DialogEditSinhVien))
                                    .addGroup(Dialog_Edit_SinhVienLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jDateNgaysinhSV_DialogEditSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(45, Short.MAX_VALUE))
                            .addGroup(Dialog_Edit_SinhVienLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditSinhVien_DialogSinhVien)
                                    .addComponent(txtCMND_DialogEditSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(Dialog_Edit_SinhVienLayout.createSequentialGroup()
                        .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel22))
                        .addGap(28, 28, 28)
                        .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dialog_Edit_SinhVienLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Dialog_Edit_SinhVienLayout.createSequentialGroup()
                                .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radioMale_DialogEditSinhVien)
                                    .addComponent(txtTenSV_DialogEditSinhVien)
                                    .addComponent(cmbLopSH_DialogEditSinhVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSVID_DialogEditSinhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(Dialog_Edit_SinhVienLayout.createSequentialGroup()
                        .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Dialog_Edit_SinhVienLayout.setVerticalGroup(
            Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_Edit_SinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSVID_DialogEditSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTenSV_DialogEditSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cmbLopSH_DialogEditSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(radioMale_DialogEditSinhVien)
                    .addComponent(radioFamale_DialogEditSinhVien))
                .addGap(15, 15, 15)
                .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jDateNgaysinhSV_DialogEditSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCMND_DialogEditSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dialog_Edit_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEditSinhVien_DialogSinhVien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dialog_Search_SinhVien.setTitle("Tìm kiếm");

        jLabel9.setText("Tên sinh viên");

        btn_SearchSV_Dialog.setText("Tìm kiếm");
        btn_SearchSV_Dialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchSV_DialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_Search_SinhVienLayout = new javax.swing.GroupLayout(Dialog_Search_SinhVien.getContentPane());
        Dialog_Search_SinhVien.getContentPane().setLayout(Dialog_Search_SinhVienLayout);
        Dialog_Search_SinhVienLayout.setHorizontalGroup(
            Dialog_Search_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Search_SinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dialog_Search_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_SearchSV_Dialog)
                    .addComponent(txt_TenSV_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dialog_Search_SinhVienLayout.setVerticalGroup(
            Dialog_Search_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_Search_SinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_Search_SinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_TenSV_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SearchSV_Dialog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sinh Viên");

        tableSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableSinhVien);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("QUẢN LÝ SINH VIÊN");

        Label_KetQuaTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Label_KetQuaTimKiem.setText("jLabel10");

        btnExit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 0, 204));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnRefreshSinhVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRefreshSinhVien.setForeground(new java.awt.Color(0, 0, 255));
        btnRefreshSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LamTuoi.png"))); // NOI18N
        btnRefreshSinhVien.setText("Làm tươi");
        btnRefreshSinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefreshSinhVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefreshSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshSinhVienActionPerformed(evt);
            }
        });

        btn_SearchSV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_SearchSV.setForeground(new java.awt.Color(0, 0, 255));
        btn_SearchSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_SearchSV.setText("Tìm Kiếm");
        btn_SearchSV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_SearchSV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_SearchSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchSVActionPerformed(evt);
            }
        });

        btnDeleteSinhVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDeleteSinhVien.setForeground(new java.awt.Color(0, 0, 204));
        btnDeleteSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnDeleteSinhVien.setText("Xóa");
        btnDeleteSinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteSinhVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSinhVienActionPerformed(evt);
            }
        });

        btnEditSinhVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEditSinhVien.setForeground(new java.awt.Color(0, 0, 204));
        btnEditSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sua.png"))); // NOI18N
        btnEditSinhVien.setText("Sửa");
        btnEditSinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditSinhVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSinhVienActionPerformed(evt);
            }
        });

        btnAddSinhVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAddSinhVien.setForeground(new java.awt.Color(51, 0, 255));
        btnAddSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Them.png"))); // NOI18N
        btnAddSinhVien.setText("Thêm");
        btnAddSinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddSinhVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSinhVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_KetQuaTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddSinhVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditSinhVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteSinhVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_SearchSV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefreshSinhVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExit)
                                .addGap(0, 820, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchSV, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(4, 4, 4)
                .addComponent(Label_KetQuaTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSinhVienActionPerformed
        try {
            // TODO add your handling code here:
            Reset();
            txtSVID_DialogAddSinhVien.setText(controller.SinhVienController.createSinhVienID());
            listLopSH = controller.LopSHController.listLopSHID();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (LopSH lopSH : listLopSH) {
                model.addElement(lopSH.getTenLopSH());
            }
            cmbLopSH_DialogAddSinhVien.setModel(model);
            radioMale_DialogAddSinhVien.setSelected(true);
            Dialog_Add_SinhVien.setSize(350,500);
            Dialog_Add_SinhVien.setLocationRelativeTo(null);
            Dialog_Add_SinhVien.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddSinhVienActionPerformed

    private void btnAddSinhVien_DialogSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSinhVien_DialogSinhVienActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            if (txtTenSV_DialogAddSinhVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên sinh viên", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtTenSV_DialogAddSinhVien.requestFocus();
                return;
            }
            
             if (txtDiachiSV_DialogAddSinhVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập địa chỉ sinh viên", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtDiachiSV_DialogAddSinhVien.requestFocus();
                return;
            }
            
                if (txtCMND_DialogAddSinhVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chua nhập số CMND sinh viên", "Thông bao", JOptionPane.ERROR_MESSAGE);
                txtCMND_DialogAddSinhVien.requestFocus();
                return;
            }
            
             try{
                long n=0L;
                n = Long.parseLong(txtCMND_DialogAddSinhVien.getText());
                if(n<0) {
                    JOptionPane.showMessageDialog(null, "Chỉ nhập số trên ô số CMND", "Thong bao", JOptionPane.ERROR_MESSAGE);
                return;
                }
            }catch(Exception ex) {
               JOptionPane.showMessageDialog(null, "Chỉ nhập số trên ô số CMND", "Thong bao", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            SinhVien sinhVien = new SinhVien();
            sinhVien.setID_SV(txtSVID_DialogAddSinhVien.getText());
            sinhVien.setTenSV(txtTenSV_DialogAddSinhVien.getText());
            for (LopSH lopSH : listLopSH) {
                if (lopSH.getTenLopSH().equalsIgnoreCase(cmbLopSH_DialogAddSinhVien.getSelectedItem().toString())) {
                    sinhVien.setLopSH(lopSH.getID_LopSH());
                }
            }
            
            if (radioMale_DialogAddSinhVien.isSelected()) {
                sinhVien.setGioitinhSV(true);
            } else {
                sinhVien.setGioitinhSV(false);
            }
            
            sinhVien.setNgaysinhSV(jDateNgaysinhSV_DialogAddSinhVien.getDate());
             
            sinhVien.setDiachiSV(txtDiachiSV_DialogAddSinhVien.getText());
            sinhVien.setCMND(txtCMND_DialogAddSinhVien.getText());
            int ketQua = controller.SinhVienController.addSinhVienID(sinhVien);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Thêm mới sinh viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLSinhVien();
                Dialog_Add_SinhVien.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Thêm mới sinh viên không thành công", "Thong bao", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddSinhVien_DialogSinhVienActionPerformed

    private void btnEditSinhVien_DialogSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSinhVien_DialogSinhVienActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            if (txtTenSV_DialogEditSinhVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập tên sinh viên", "Thông báo", JOptionPane.ERROR_MESSAGE);
                txtTenSV_DialogEditSinhVien.requestFocus();
                return;
            }
            
           
             if (txtDiachiSV_DialogEditSinhVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chưa nhập địa chỉ sinh viên", "Thong bao", JOptionPane.ERROR_MESSAGE);
                txtDiachiSV_DialogEditSinhVien.requestFocus();
                return;
            }
            
              if (txtCMND_DialogEditSinhVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Chua nhập số CMND sinh viên", "Thông bao", JOptionPane.ERROR_MESSAGE);
                txtCMND_DialogEditSinhVien.requestFocus();
                return;
            }
             
             
             try{
                long n=0L;
                n = Long.parseLong(txtCMND_DialogEditSinhVien.getText().trim());
                if(n<0) {
                    JOptionPane.showMessageDialog(null, "Chỉ nhập số trên ô số CMND", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
                }
            }catch(Exception ex) {
               JOptionPane.showMessageDialog(null, "Chỉ nhập số trên ô số CMND", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
             
            SinhVien sinhVien = new SinhVien();
            sinhVien.setID_SV(txtSVID_DialogEditSinhVien.getText());
            sinhVien.setTenSV(txtTenSV_DialogEditSinhVien.getText());
            sinhVien.setCMND(txtCMND_DialogEditSinhVien.getText());
            for (LopSH lopSH : listLopSH) {
                if (lopSH.getTenLopSH().equalsIgnoreCase(cmbLopSH_DialogEditSinhVien.getSelectedItem().toString())) {
                    sinhVien.setLopSH(lopSH.getID_LopSH());
                }
            }
            if (radioMale_DialogEditSinhVien.isSelected()) {
                sinhVien.setGioitinhSV(true);
            } else {
                sinhVien.setGioitinhSV(false);
            }
            
           sinhVien.setNgaysinhSV(jDateNgaysinhSV_DialogEditSinhVien.getDate());
         
         
            sinhVien.setDiachiSV(txtDiachiSV_DialogEditSinhVien.getText());
            
            int ketQua = controller.SinhVienController.editSinhVienID(sinhVien);
            if (ketQua > 0) {
                JOptionPane.showMessageDialog(null, "Sửa sinh viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                Run_QLSinhVien();
                Dialog_Edit_SinhVien.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Sửa sinh viên không thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEditSinhVien_DialogSinhVienActionPerformed

    private void btnEditSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSinhVienActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            int selectedRow = tableSinhVien.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Chưa chọn sinh viên cần sửa", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            txtSVID_DialogEditSinhVien.setText(tableSinhVien.getValueAt(selectedRow, 0).toString());
            listLopSH = controller.LopSHController.listLopSHID();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (LopSH lopSH : listLopSH) {
                model.addElement(lopSH.getTenLopSH());
            }
            cmbLopSH_DialogEditSinhVien.setModel(model);
            cmbLopSH_DialogEditSinhVien.setSelectedItem(tableSinhVien.getValueAt(selectedRow, 2));
            if (tableSinhVien.getValueAt(selectedRow, 3).toString().equalsIgnoreCase("nam")) {
                radioMale_DialogEditSinhVien.setSelected(true);
            } else {
                radioFamale_DialogEditSinhVien.setSelected(true);
            }
            txtTenSV_DialogEditSinhVien.setText(tableSinhVien.getValueAt(selectedRow, 1).toString());
            
              txtCMND_DialogEditSinhVien.setText(tableSinhVien.getValueAt(selectedRow, 4).toString());
            
            //jDateNgaysinhSV_DialogEditSinhVien.setDate(new java.util.Date(tableSinhVien.getValueAt(selectedRow, 4).toString().replaceAll("-", "/")));
            
             try
                {       
                        Date date = new SimpleDateFormat("dd/MM/yyyy").parse((String)tableSinhVien.getValueAt(selectedRow,5).toString());
                        this.jDateNgaysinhSV_DialogEditSinhVien.setDate(date);
                }catch(Exception e)
                {
                    e.printStackTrace();
                }
         
             
            
            
            txtDiachiSV_DialogEditSinhVien.setText(tableSinhVien.getValueAt(selectedRow, 6).toString());
            Dialog_Edit_SinhVien.setSize(350,500);
            Dialog_Edit_SinhVien.setLocationRelativeTo(null);
            Dialog_Edit_SinhVien.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEditSinhVienActionPerformed

    private void btnDeleteSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSinhVienActionPerformed
        // TODO add your handling code here:
          if (tableSinhVien.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn sinh viên cần xóa!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String SVID = tableSinhVien.getValueAt(tableSinhVien.getSelectedRow(), 0).toString();
                if (controller.SinhVienController.deleteSinhVienID(SVID) == 1) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công sinh viên có ID " + SVID, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    Run_QLSinhVien();
                
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa không thành công sinh viên có ID " + SVID, "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(frmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteSinhVienActionPerformed

    private void btnRefreshSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshSinhVienActionPerformed
        // TODO add your handling code here:
        Run_QLSinhVien();
    }//GEN-LAST:event_btnRefreshSinhVienActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btn_SearchSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchSVActionPerformed
        // TODO add your handling code here:
       
            // TODO add your handling code here:
           
            txt_TenSV_Search.setText("");
            Dialog_Search_SinhVien.setSize(350,125);
            Dialog_Search_SinhVien.setLocationRelativeTo(null);
            Dialog_Search_SinhVien.setVisible(true);
            
  
    }//GEN-LAST:event_btn_SearchSVActionPerformed

    private void btn_SearchSV_DialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchSV_DialogActionPerformed
        // TODO add your handling code here:
        try {
            List<LopSH> listLopSH = controller.LopSHController.listLopSHID();
            Vector tieuDe = new Vector();
            tieuDe.add("Mã sinh viên");
            tieuDe.add("Tên sinh viên");
            tieuDe.add("Lớp SH");
            tieuDe.add("Giới tính");
            tieuDe.add("Số CMND");
            tieuDe.add("Ngày sinh");
            tieuDe.add("Địa chỉ");
            Vector duLieu = new Vector();
            String TenSV = new String();
            TenSV= txt_TenSV_Search.getText();
            Label_KetQuaTimKiem.setText("Kết quả tìm kiếm tên sinh viên theo từ khóa: "+TenSV+". Nhấn làm tươi để xem tất cả sinh viên");
            List<SinhVien> listSinhVien = controller.SinhVienController.TimKiemSVTen(TenSV);
            if (listSinhVien != null) {
                for (SinhVien sinhVien : listSinhVien) {
                    Vector tam = new Vector();
                    tam.add(sinhVien.getID_SV());
                    tam.add(sinhVien.getTenSV());
                    for (LopSH lopSH : listLopSH) {
                        if (lopSH.getID_LopSH().equalsIgnoreCase(sinhVien.getLopSH())) {
                            tam.add(lopSH.getTenLopSH());
                            break;
                        }
                    }
                    if (sinhVien.isGioitinhSV()) {
                        tam.add("Nam");
                    } else {
                        tam.add("Nữ");
                    }
                    tam.add(sinhVien.getCMND());
                    
                    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                    String strDate = formatter.format(sinhVien.getNgaysinhSV());
                    tam.add(strDate);

                    tam.add(sinhVien.getDiachiSV());
                    duLieu.add(tam);
                }
            }
            DefaultTableModel model = new DefaultTableModel(duLieu, tieuDe);
            tableSinhVien.setModel(model);
            Dialog_Search_SinhVien.dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_SearchSV_DialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Window look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_Add_SinhVien;
    private javax.swing.JDialog Dialog_Edit_SinhVien;
    private javax.swing.JDialog Dialog_Search_SinhVien;
    private javax.swing.JLabel Label_KetQuaTimKiem;
    private javax.swing.JButton btnAddSinhVien;
    private javax.swing.JButton btnAddSinhVien_DialogSinhVien;
    private javax.swing.JButton btnDeleteSinhVien;
    private javax.swing.JButton btnEditSinhVien;
    private javax.swing.JButton btnEditSinhVien_DialogSinhVien;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefreshSinhVien;
    private javax.swing.JButton btn_SearchSV;
    private javax.swing.JButton btn_SearchSV_Dialog;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbLopSH_DialogAddSinhVien;
    private javax.swing.JComboBox<String> cmbLopSH_DialogEditSinhVien;
    private com.toedter.calendar.JDateChooser jDateNgaysinhSV_DialogAddSinhVien;
    private com.toedter.calendar.JDateChooser jDateNgaysinhSV_DialogEditSinhVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton radioFamale_DialogAddSinhVien;
    private javax.swing.JRadioButton radioFamale_DialogEditSinhVien;
    private javax.swing.JRadioButton radioMale_DialogAddSinhVien;
    private javax.swing.JRadioButton radioMale_DialogEditSinhVien;
    private javax.swing.JTable tableSinhVien;
    private javax.swing.JTextField txtCMND_DialogAddSinhVien;
    private javax.swing.JTextField txtCMND_DialogEditSinhVien;
    private javax.swing.JTextArea txtDiachiSV_DialogAddSinhVien;
    private javax.swing.JTextArea txtDiachiSV_DialogEditSinhVien;
    private javax.swing.JTextField txtSVID_DialogAddSinhVien;
    private javax.swing.JTextField txtSVID_DialogEditSinhVien;
    private javax.swing.JTextField txtTenSV_DialogAddSinhVien;
    private javax.swing.JTextField txtTenSV_DialogEditSinhVien;
    private javax.swing.JTextField txt_TenSV_Search;
    // End of variables declaration//GEN-END:variables
}
