//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Batch155SMSOnline3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active
    {
        public int Id { get; set; }
        public Nullable<int> IdService { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> StartService { get; set; }
        public Nullable<System.DateTime> EndService { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Service Service { get; set; }
    }
}
