//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Batch155SMSOnline3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Actives = new HashSet<Active>();
        }
    
        public int Id { get; set; }
        public string ServiceName { get; set; }
        public string ServiceImage { get; set; }
        public Nullable<int> IdLevel { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> StopServices { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active> Actives { get; set; }
        public virtual LevelService LevelService { get; set; }
        public virtual User User { get; set; }
    }
}
